### ISSUE TITLE
提交上线单后置任务报错问题

### ISSUE THREAD

**Issue by che0929** [meolu/walle-web#1012]
**问题描述**
ls -t 3_* | tail -n +21 | xargs rm -rf
rm: invalid option -- '1'
Try 'rm --help' for more information.

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
[2019-09-10 14:54:07,322] ERROR in deployer: rm: invalid option -- '1'
Try 'rm --help' for more information.
Traceback (most recent call last):
  File "/var/www/walle-web/walle/service/deployer.py", line 498, in walle_deploy
    self.post_release(self.connections[self.task_id])
  File "/var/www/walle-web/walle/service/deployer.py", line 358, in post_release
    self.cleanup_remote(waller)
  File "/var/www/walle-web/walle/service/deployer.py", line 440, in cleanup_remote
    result = waller.run(command, wenv=self.config())
  File "/var/www/walle-web/walle/service/waller.py", line 128, in run
```
**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. aba77b36] walle首页信息处显示

**解决方案**
walle/service/deployer.py 文件 437行 "rm -rf " 改成 “rm -rf --”

**Comment by ZouHongxue** [comment]
测试没有问题，请检查你的命令是否在某处不小心带了个 `1`导致。
![image](https://user-images.githubusercontent.com/20573881/67629116-a8b4df00-f8ac-11e9-86d9-4b663f611ffb.png)
