### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by zhaozkx** [meolu/walle-web#1022]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`super超管`角色下，项目管理页面，编辑项目成员，提交失败，报错：用户不存在于空间用户组中

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
Server initialized for gevent.
Exception in thread socket_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/walle-web/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 556, in run
    self.wsgi_server.serve_forever()
  File "/app/walle-web/venv/local/lib/python2.7/site-packages/gevent/baseserver.py", line 362, in serve_forever
    self.start()
  File "/app/walle-web/venv/local/lib/python2.7/site-packages/gevent/baseserver.py", line 306, in start
    self.init_socket()
  File "/app/walle-web/venv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 1487, in init_socket
    StreamServer.init_socket(self)
  File "/app/walle-web/venv/local/lib/python2.7/site-packages/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/app/walle-web/venv/local/lib/python2.7/site-packages/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/app/walle-web/venv/local/lib/python2.7/site-packages/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
error: [Errno 99] Cannot assign requested address: ('web.zhao.xin', 5000)
```
logs/error.log
```
这个日志是空的
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. ubuntu18.04]
 - 版本 [e.g. aba77b36] walle首页信息处显示

**Comment by ZouHongxue** [comment]
这个log是启动时log，问题模板没有任何改动。
请按照模板详细描述问题。
