### ISSUE TITLE
用nohup 启动tomcat，发布成功了，但是显示任务上线失败

### ISSUE THREAD

**Issue by free7473** [meolu/walle-web#1028]
Release后置任务命令
set -m
nohup ${TOMCAT_HOME}/bin/startup.sh &
上服务器上看了，远程已经执行成功了，但是还是显示上线失败，不用nohup，tomcat会启动不成功

**Comment by ZouHongxue** [comment]
请查查日志，贴出来

**Comment by free7473** [comment]
2019-10-28 09:10:23,460 ERROR /usr/app/walle-web/walle/service/waller.py 92 waller.run 
Saw 1 exceptions within threads (NotImplementedError):


Thread args: {'kwargs': {'echo': None,
            'input_': <open file '<stdin>', mode 'r' at 0x7f9ec18450c0>,
            'output': <open file '<stdout>', mode 'w' at 0x7f9ec1845150>},
 'target': <bound method Remote.handle_stdin of <fabric2.runners.Remote object at 0x7f9ead027d90>>}

Traceback (most recent call last):

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 706, in handle_stdin
    self.close_proc_stdin()

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 939, in close_proc_stdin
    raise NotImplementedError

NotImplementedError

Traceback (most recent call last):
  File "/usr/app/walle-web/walle/service/waller.py", line 53, in run
    result = super(Waller, self).run(command, pty=pty, warn=True, watchers=[say_yes()], env=self.custom_global_env, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/fabric2/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/fabric2/connection.py", line 628, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 399, in _run_body
    raise ThreadException(thread_exceptions)
ThreadException: 
Saw 1 exceptions within threads (NotImplementedError):


Thread args: {'kwargs': {'echo': None,
            'input_': <open file '<stdin>', mode 'r' at 0x7f9ec18450c0>,
            'output': <open file '<stdout>', mode 'w' at 0x7f9ec1845150>},
 'target': <bound method Remote.handle_stdin of <fabric2.runners.Remote object at 0x7f9ead027d90>>}

Traceback (most recent call last):

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 706, in handle_stdin
    self.close_proc_stdin()

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 939, in close_proc_stdin
    raise NotImplementedError

NotImplementedError


2019-10-28 09:10:23,504 ERROR /usr/app/walle-web/walle/service/waller.py 111 waller.run task_id=24, user:root host:176.10.10.230 command:nohup ${TOMCAT_HOME}/bin/startup.sh &, status=1, message:
Traceback (most recent call last):
  File "/usr/app/walle-web/walle/service/waller.py", line 53, in run
    result = super(Waller, self).run(command, pty=pty, warn=True, watchers=[say_yes()], env=self.custom_global_env, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/fabric2/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/fabric2/connection.py", line 628, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 399, in _run_body
    raise ThreadException(thread_exceptions)
ThreadException: 
Saw 1 exceptions within threads (NotImplementedError):


Thread args: {'kwargs': {'echo': None,
            'input_': <open file '<stdin>', mode 'r' at 0x7f9ec18450c0>,
            'output': <open file '<stdout>', mode 'w' at 0x7f9ec1845150>},
 'target': <bound method Remote.handle_stdin of <fabric2.runners.Remote object at 0x7f9ead027d90>>}

Traceback (most recent call last):

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 706, in handle_stdin
    self.close_proc_stdin()

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 939, in close_proc_stdin
    raise NotImplementedError

NotImplementedError


2019-10-28 09:10:23,508 ERROR /usr/app/walle-web/walle/service/deployer.py 505 deployer.walle_deploy 
Saw 1 exceptions within threads (NotImplementedError):


Thread args: {'kwargs': {'echo': None,
            'input_': <open file '<stdin>', mode 'r' at 0x7f9ec18450c0>,
            'output': <open file '<stdout>', mode 'w' at 0x7f9ec1845150>},
 'target': <bound method Remote.handle_stdin of <fabric2.runners.Remote object at 0x7f9ead027d90>>}

Traceback (most recent call last):

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 706, in handle_stdin
    self.close_proc_stdin()

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 939, in close_proc_stdin
    raise NotImplementedError

NotImplementedError

Traceback (most recent call last):
  File "/usr/app/walle-web/walle/service/deployer.py", line 498, in walle_deploy
    self.post_release(self.connections[self.task_id])
  File "/usr/app/walle-web/walle/service/deployer.py", line 353, in post_release
    result = waller.run(command, wenv=self.config(), pty=pty)
  File "/usr/app/walle-web/walle/service/waller.py", line 128, in run
    raise e
ThreadException: 
Saw 1 exceptions within threads (NotImplementedError):


Thread args: {'kwargs': {'echo': None,
            'input_': <open file '<stdin>', mode 'r' at 0x7f9ec18450c0>,
            'output': <open file '<stdout>', mode 'w' at 0x7f9ec1845150>},
 'target': <bound method Remote.handle_stdin of <fabric2.runners.Remote object at 0x7f9ead027d90>>}

Traceback (most recent call last):

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 706, in handle_stdin
    self.close_proc_stdin()

  File "/usr/app/walle-web/venv/lib/python2.7/site-packages/invoke/runners.py", line 939, in close_proc_stdin
    raise NotImplementedError

NotImplementedError

**Comment by xingyueGK** [comment]
这个是fabric2 的一个bug nohup 后面加一个sleep 1就可以了

**Comment by ZouHongxue** [comment]
> 这个是fabric2 的一个bug nohup 后面加一个sleep 1就可以了

可以给个示例吗，是像  nohup command &; sleep 1 还是其他的写法

**Comment by xingyueGK** [comment]
就这样就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "邹洪学"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 晚上6:12
收件人: "meolu/walle-web"<walle-web@noreply.github.com&gt;; 
抄送: "奔跑的小胖子"<a413728161@vip.qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [meolu/walle-web] 用nohup 启动tomcat，发布成功了，但是显示任务上线失败 (#1028)



 
这个是fabric2 的一个bug nohup 后面加一个sleep 1就可以了
  
可以给个示例吗，是像  nohup command &amp;; sleep 1 还是其他的写法

**Comment by Joseph9499** [comment]
请问 用 nohup command &; sleep 1  页面会显示发布成功了吗？

**Comment by xingyueGK** [comment]
会的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph9499"<notifications@github.com&gt;; 
发送时间: 2020年1月3日(星期五) 上午10:33
收件人: "meolu/walle-web"<walle-web@noreply.github.com&gt;; 
抄送: "奔跑的小胖子"<a413728161@vip.qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [meolu/walle-web] 用nohup 启动tomcat，发布成功了，但是显示任务上线失败 (#1028)




请问 用 nohup command &amp;; sleep 1  页面会显示发布成功了吗？

**Comment by Joseph9499** [comment]
#启动
set -m
nohup  command  ${TOMCAT_HOME}/bin/startup.sh  &amp; sleep 1 


我这样配置还是页面还是现实发布失败，但是tomcat服务已经启动了

**Comment by Joseph9499** [comment]
> 会的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Joseph9499"<notifications@github.com&gt;; 发送时间: 2020年1月3日(星期五) 上午10:33 收件人: "meolu/walle-web"<walle-web@noreply.github.com&gt;; 抄送: "奔跑的小胖子"<a413728161@vip.qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [meolu/walle-web] 用nohup 启动tomcat，发布成功了，但是显示任务上线失败 (#1028) 请问 用 nohup command &amp;; sleep 1 页面会显示发布成功了吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.


![image](https://user-images.githubusercontent.com/37842341/71705175-39fa8180-2e19-11ea-9535-2b70074fc83b.png)

**Comment by BILLFuYiWei** [comment]
遇到相同问题 这个问题有解决的办法了吗？ 这是我的提的 https://github.com/meolu/walle-web/issues/1123
