### ISSUE TITLE
sh admin.sh migration  flask db upgrade

### ISSUE THREAD

**Issue by 935345515** [meolu/walle-web#1055]
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "waller", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/app/walle-web/waller.py", line 6, in <module>
    from walle.app import create_app
  File "/home/app/walle-web/walle/app.py", line 3, in <module>
    import gevent.monkey
ImportError: No module named gevent.monkey

Migration:                 [ fail ]

**Comment by zjy200809** [comment]
同样的错误，同求如何解决

**Comment by zjy200809** [comment]
重新安装了系统，没有再装Python3.5，只用系统自带的python2.7（centos7的）。然后就在sh admin.sh init报错，修改一下。后面跑这一个没有出现问题了。

**Comment by workbourne** [comment]
> 重新安装了系统，没有再装Python3.5，只用系统自带的python2.7（centos7的）。然后就在sh admin.sh init报错，修改一下。后面跑这一个没有出现问题了。

意思，出现这个错误，要放弃了吗？重装系统，那只有放弃了

**Comment by zjy200809** [comment]
不想折腾，因为机器没有啥其它的，就直接重装，没有问题，其实装得很快的。
