### ISSUE TITLE
No module named flask.helpers

### ISSUE THREAD

**Issue by SuperHaoHaoHao** [meolu/walle-web#1068]
查看 `walle` 日志报错 `flask.helpers` 或者 `No such command "db"`
日志类似如下：
```
Traceback (most recent call last):
File "waller.py", line 5, in <module>
from flask.helpers import get_ debug_ flag 
ImportError: No module named flask.helpers
```

检查 `sh admin.sh init` 初始化时是否最后有报错：
`ERROR: Package 'gunicorn' requires a different Python: 2.7.5 not in '>=3.4'`

`python`环境是2.7+ 需要把`/walle-web/requirements/prod.txt` 这个文件里的
```
# Deployment
gunicorn>=19.1.1  改成 gunicorn==19.1.1
```
然后重新初始化 `sh admin.sh init` 再去执行初始化部署

如果能帮到你，请回来回复，活跃问题让更多人看到解决方法。

**Comment by SuperHaoHaoHao** [comment]
如果还是不行 `pip list` 检查一下是否有 `flask-helpers`
如果没有 `pip install flask-helpers` 安装后再尝试部署 `sh admin.sh init`

**Comment by pptfz** [comment]
全部尝试完成后 继续报错 没有用
```
Traceback (most recent call last):
  File "waller.py", line 5, in <module>
    from flask.helpers import get_debug_flag
ImportError: No module named flask.helpers
```

**Comment by awanganddong** [comment]
```
# -*- coding: utf-8 -*-
"""Create an application instance."""
import sys

from flask import Flask. //新增这句代码
from flask.helpers import get_debug_flag
from walle.app import create_app
from walle.config.settings_dev import DevConfig
from walle.config.settings_test import TestConfig
from walle.config.settings_prod import ProdConfig

CONFIG = DevConfig if get_debug_flag() else ProdConfig

if len(sys.argv) > 2 and sys.argv[2] == 'test':
    CONFIG = TestConfig

app = create_app(CONFIG)

```
