### ISSUE TITLE
Migration:                 [ fail ]

### ISSUE THREAD

**Issue by balingmo403** [meolu/walle-web#1089]
**问题描述**
标准部署
初始化数据库失败 centos7 最新版本

----------------
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "waller", an ImportError was raised:

Traceback (most recent call last):
  File "/opt/walle-web-master/venv/lib/python2.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/opt/walle-web-master/waller.py", line 6, in <module>
    from walle.app import create_app
  File "/opt/walle-web-master/walle/app.py", line 16, in <module>
    from walle.api import deploy as DeployAPI
  File "/opt/walle-web-master/venv/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/opt/walle-web-master/walle/api/deploy.py", line 14, in <module>
    from walle.service.deployer import Deployer
  File "/opt/walle-web-master/venv/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/opt/walle-web-master/walle/service/deployer.py", line 25, in <module>
    from walle.service.git.repo import Repo
  File "/opt/walle-web-master/venv/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/opt/walle-web-master/walle/service/git/repo.py", line 14, in <module>
    import git as PyGit
  File "/opt/walle-web-master/venv/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/opt/walle-web-master/venv/lib/python2.7/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

Migration:                 [ fail ]

**Comment by AmalsCode** [comment]
### **在使用中同样遇到了此问题, 排查过程中上述报错信息结尾处给出了答案:**
All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
- quiet|q|silence|s|none|n|0: for no warning or exception
- warn|w|warning|1: for a printed warning
- error|e|raise|r|2: for a raised exception

Example:
export GIT_PYTHON_REFRESH=quiet

Migration: [ fail ]

### **错误信息提示:**
All git commands will error until this is rectified.
(翻译: 在纠正之前，所有git命令都将出错)

**解决方案(系统AliYun - CentOS 7):**
编辑 vim /etc/profile
添加 export GIT_PYTHON_REFRESH=quiet
更新 source /etc/profile

### **mysql连接规则:**
mysql://账号:密码@IP:端口/数据库?charset=utf8mb4
