### ISSUE TITLE
执行sh admin.sh migration报错

### ISSUE THREAD

**Issue by opszone** [meolu/walle-web#1095]
问题描述
部署环境：CentOS  7.2  python 2.7 MariaDB 10.3.22
第一步： sh admin.sh init没有问题;
第二步: 修改walle/config/settings_prod.py 也改了
第三步：执行 sh admin.sh migration时报错：
Migration walle
----------------
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "waller", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/data/www/walle-web-master/waller.py", line 6, in <module>
    from walle.app import create_app
  File "/data/www/walle-web-master/walle/app.py", line 16, in <module>
    from walle.api import deploy as DeployAPI
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/data/www/walle-web-master/walle/api/deploy.py", line 14, in <module>
    from walle.service.deployer import Deployer
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/data/www/walle-web-master/walle/service/deployer.py", line 24, in <module>
    from walle.service.waller import Waller
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/data/www/walle-web-master/walle/service/waller.py", line 9, in <module>
    from fabric2 import Connection
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric2/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric2/connection.py", line 17, in <module>
    from paramiko.agent import AgentRequestHandler
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 91, in <module>
    from paramiko.kex_curve25519 import KexCurve25519
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/paramiko/kex_curve25519.py", line 6, in <module>
    from cryptography.hazmat.primitives.asymmetric.x25519 import (
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named x25519

Migration:                 [ fail ]

**Comment by baoming158** [comment]
没有人处理bug吗？？？这代码下载后根本不能安装啊

**Comment by linux724** [comment]
是呀。我下载完也遇到一堆问题。我现在已经换成另外一个开源平台了。基本上可以满足所有发布需求。https://github.com/openspug/spug
