### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by baoming158** [meolu/walle-web#1098]
**问题描述**
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: virtualenv in /home/ubuntu/.local/lib/python2.7/site-packages (20.0.10)
Requirement already satisfied: distlib<1,>=0.3.0 in /home/ubuntu/.local/lib/python2.7/site-packages (from virtualenv) (0.3.0)
Requirement already satisfied: filelock<4,>=3.0.0 in /home/ubuntu/.local/lib/python2.7/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: importlib-resources<2,>=1.0; python_version < "3.7" in /home/ubuntu/.local/lib/python2.7/site-packages (from virtualenv) (1.3.1)
Requirement already satisfied: six<2,>=1.9.0 in /home/ubuntu/.local/lib/python2.7/site-packages (from virtualenv) (1.14.0)
Requirement already satisfied: pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32" in /home/ubuntu/.local/lib/python2.7/site-packages (from virtualenv) (2.3.5)
Requirement already satisfied: contextlib2<1,>=0.6.0; python_version < "3.3" in /home/ubuntu/.local/lib/python2.7/site-packages (from virtualenv) (0.6.0.post1)
Requirement already satisfied: appdirs<2,>=1.4.3 in /home/ubuntu/.local/lib/python2.7/site-packages (from virtualenv) (1.4.3)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in /home/ubuntu/.local/lib/python2.7/site-packages (from virtualenv) (1.5.0)
Requirement already satisfied: singledispatch; python_version < "3.4" in /home/ubuntu/.local/lib/python2.7/site-packages (from importlib-resources<2,>=1.0; python_version < "3.7"->virtualenv) (3.4.0.3)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in /home/ubuntu/.local/lib/python2.7/site-packages (from importlib-resources<2,>=1.0; python_version < "3.7"->virtualenv) (1.2.0)
Requirement already satisfied: typing; python_version < "3.5" in /home/ubuntu/.local/lib/python2.7/site-packages (from importlib-resources<2,>=1.0; python_version < "3.7"->virtualenv) (3.7.4.1)
Requirement already satisfied: scandir; python_version < "3.5" in /home/ubuntu/.local/lib/python2.7/site-packages (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv) (1.10.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /home/ubuntu/.local/lib/python2.7/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv) (4.0.2)
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython2-posix}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list]
                  [--clear] [--system-site-packages] [--symlinks | --copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel]
                  [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: unrecognized arguments: --no-site-packages
admin.sh: line 43: ./venv/bin/activate: No such file or directory

**问题描述**
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Traceback (most recent call last):
  File "waller.py", line 6, in <module>
    from walle.app import create_app
  File "/home/ubuntu/baoming/walle/walle-web/walle/app.py", line 16, in <module>
    from walle.api import deploy as DeployAPI
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/baoming/walle/walle-web/walle/api/deploy.py", line 14, in <module>
    from walle.service.deployer import Deployer
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/baoming/walle/walle-web/walle/service/deployer.py", line 25, in <module>
    from walle.service.git.repo import Repo
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/baoming/walle/walle-web/walle/service/git/repo.py", line 14, in <module>
    import git as PyGit
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named compat
```


**截图**





**运行环境**
 - OS: [e.g. ubuntu]

**Comment by linux724** [comment]
我安装也报错了。无法解决。后来看到https://github.com/openspug/spug 这个平台，就换这个了。
