### ISSUE TITLE
安装报错（sh admin.sh migration）

### ISSUE THREAD

**Issue by baoming158** [meolu/walle-web#1099]
**问题描述**
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "waller", an ImportError was raised:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/ubuntu/baoming/walle/walle-web/waller.py", line 6, in <module>
    from walle.app import create_app
  File "/home/ubuntu/baoming/walle/walle-web/walle/app.py", line 16, in <module>
    from walle.api import deploy as DeployAPI
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/baoming/walle/walle-web/walle/api/deploy.py", line 14, in <module>
    from walle.service.deployer import Deployer
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/baoming/walle/walle-web/walle/service/deployer.py", line 25, in <module>
    from walle.service.git.repo import Repo
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/baoming/walle/walle-web/walle/service/git/repo.py", line 14, in <module>
    import git as PyGit
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named compat

Migration:                 [ fail ]

**运行环境**
 - OS: [e.g. ubuntu]

**Comment by VictorDeping** [comment]
我也遇到这个错误了，问题解决了吗

**Comment by linux724** [comment]
我安装也遇到错误了。不知道如何解决。
不过我又找到一个很好用的开源运维平台，基本上可以满足所有发布需求。https://github.com/openspug/spug

**Comment by baoming158** [comment]
> 我也遇到这个错误了，问题解决了吗

没解决，这个平台不好用啊，作者都不回复！

**Comment by wzbooks** [comment]
我也遇到了，以为是自己的问题搞了一天，没想到大家都遇到了。。。

**Comment by workbourne** [comment]
这个问题让我把walle安装了很多遍，各种试，就是不行。有解决的回复下啊，感谢

**Comment by maginaro** [comment]
参考
https://github.com/NervanaSystems/distiller/issues/475

$ pip uninstall gitdb2
$ pip install gitdb2==2.0.6

**Comment by workbourne** [comment]
> 参考
> [NervanaSystems / distiller＃475](https://github.com/NervanaSystems/distiller/issues/475)
> 
> $ pip卸载gitdb2
> $ pip安装gitdb2 == 2.0.6

谢谢，下次试下
