### ISSUE TITLE
sh admin.sh migration

### ISSUE THREAD

**Issue by workbourne** [meolu/walle-web#1105]
Migration walle
----------------
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "waller", an ImportError was raised:

Traceback (most recent call last):

**Comment by linux724** [comment]
可以了解一下另外一个开源好用的运维平台：https://github.com/openspug/spug

**Comment by workbourne** [comment]
> 可以了解一下另外一个开源好用的运维平台：https://github.com/openspug/spug

你这个我也用了，数据初始化就报错，执行不 下去。
python manage.py initdb

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    main()
  File "manage.py", line 20, in main
    execute_from_command_line(sys.argv)
。。。。。。。。。
site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).

**Comment by linux724** [comment]
最新版本有脚本一键安装，docker一键安装。不需要你自己初始化了。

**Comment by lingcarzy** [comment]
> 
> 
> > 可以了解一下另外一个开源好用的运维平台：https://github.com/openspug/spug
> 
> 你这个我也用了，数据初始化就报错，执行不 下去。
> python manage.py initdb
> 
> Traceback (most recent call last):
> File "manage.py", line 24, in
> main()
> File "manage.py", line 20, in main
> execute_from_command_line(sys.argv)
> 。。。。。。。。。
> site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
> raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
> django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).

需要手动升级sqlite的版本，升级好了就可以了

**Comment by workbourne** [comment]
> > > 可以了解一下另外一个开源好用的运维平台：https://github.com/openspug/spug
> > 
> > 
> > 你这个我也用了，数据初始化就报错，执行不 下去。
> > python manage.py initdb
> > Traceback (most recent call last):
> > File "manage.py", line 24, in
> > main()
> > File "manage.py", line 20, in main
> > execute_from_command_line(sys.argv)
> > 。。。。。。。。。
> > site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
> > raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
> > django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
> 
> 需要手动升级sqlite的版本，升级好了就可以了

谢谢，下次我试一下
