### ISSUE TITLE
not a valid RSA private key file

### ISSUE THREAD

**Issue by jeiry** [meolu/walle-web#1117]
[2020-06-09 17:43:03,384] ERROR in waller: not a valid RSA private key file
Traceback (most recent call last):
File "/opt/walle_home/walle/service/waller.py", line 53, in run
result = super(Waller, self).run(command, pty=pty, warn=True, watchers=[say_yes()], env=self.custom_global_env, **kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python2.7/site-packages/fabric2/connection.py", line 29, in opens
self.open()
File "/usr/local/lib/python2.7/site-packages/fabric2/connection.py", line 541, in open
self.client.connect(**kwargs)
File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
passphrase,
File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 749, in _auth
raise saved_exception
SSHException: not a valid RSA private key file
[2020-06-09 17:43:03,392] ERROR in waller: task_id=1, user:root host:t.yoyolife.fun command:mkdir -p /data/releases/xxx, status=1, message:not a valid RSA private key file
Traceback (most recent call last):
File "/opt/walle_home/walle/service/waller.py", line 53, in run
result = super(Waller, self).run(command, pty=pty, warn=True, watchers=[say_yes()], env=self.custom_global_env, **kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python2.7/site-packages/fabric2/connection.py", line 29, in opens
self.open()
File "/usr/local/lib/python2.7/site-packages/fabric2/connection.py", line 541, in open
self.client.connect(**kwargs)
File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
passphrase,
File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 749, in _auth
raise saved_exception
SSHException: not a valid RSA private key file
emitting event "console" to 1 [/walle]

a02dc4543d2447deaab65d5aae6d6e0d: Sending packet MESSAGE data 2/walle,["console",{"data":{"status":1,"host":"t.yoyolife.fun","error":"not a valid RSA private key file","user":"root","success":"","sequence":4,"cmd":"mkdir -p /data/releases/xxx","stage":"prev_release"},"event":"console"}]
[2020-06-09 17:43:03,393] ERROR in deployer: not a valid RSA private key file
Traceback (most recent call last):
File "/opt/walle_home/walle/service/deployer.py", line 558, in walle_deploy
self.prev_release(self.connections[self.task_id])
File "/opt/walle_home/walle/service/deployer.py", line 261, in prev_release
result = waller.run(command, wenv=self.config())
File "/opt/walle_home/walle/service/waller.py", line 128, in run
raise e
SSHException: not a valid RSA private key file
emitting event "fail" to 1 [/walle]

walle是用docker安装的
walle-nginx 和 walle-python 和宿主机 三个容器都已经做好了 ssh-keygen
并已经成功的不用用户名密码分别ssh到目标服务器
但walle Release前置任务 的时候还是 not a valid RSA private key file

有人知道这是为什么吗？

**截图**
拖拽到此处即可上传
![image](https://user-images.githubusercontent.com/1124237/84132003-ec450d80-aa77-11ea-8370-172bd4a40231.png)

**运行环境**
 - 目标OS: Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64
 - 版本 walle 版本 walle commit
c3625aa5
2.0.1

**Comment by wangbaocongnb** [comment]
同样是docker部署，我也遇到了这个问题

解决办法可以参考一下:
```
1. docker exec -it walle-python bash
2. cd /root/.ssh/
3. ssh-keygen -t rsa -C "xxx@mail.cn"
4. 重新测试服务器连接，成功
```

**Comment by jeiry** [comment]
解决了，是自己sb 在配置服务器管理时 用户名没写对

**Comment by kowinner12** [comment]
参考ghost 
docker 容器里的ssh key信息需要重新生成，然后远程机器加入可信列表就可以成功了
