### ISSUE TITLE
已解决----高级任务-Release后置任务 显示失败/但是项目启动成功里

### ISSUE THREAD

**Issue by BILLFuYiWei** [meolu/walle-web#1123]
**问题描述**
owener角色 部署上线单  ”高级任务-Release后置任务 “ 在使用nohup java -jar xx.jar >> /dev/null 2>&1 & 启动spring boot项目的时候出现的问题 , 但是项目在服务器上已正常启动了
**问题描述**
这是错误日志:
2020-07-09 21:17:28,303 ERROR /usr/local/nginx/html/walle-web/walle/service/waller.py 111 waller.run task_id=27, user:root host:172.19.54.135 command:source /etc/profile;nohup java -jar -Xmx512m -Xss251k  ${PROJECT_PATH}/${SERVICE} >>  /dev/null 2>&1 &, status=1, message:
Traceback (most recent call last):
  File "/usr/local/nginx/html/walle-web/walle/service/waller.py", line 53, in run
    result = super(Waller, self).run(command, pty=pty, warn=True, watchers=[say_yes()], env=self.custom_global_env, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric2/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric2/connection.py", line 628, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 363, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 422, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 474, in _finish
    raise ThreadException(thread_exceptions)
ThreadException: 
Saw 1 exceptions within threads (NotImplementedError):

Thread args: {'kwargs': {'echo': None,
            'input_': <open file '<stdin>', mode 'r' at 0x7f28a30a40c0>,
            'output': <open file '<stdout>', mode 'w' at 0x7f28a30a4150>},
 'target': <bound method Remote.handle_stdin of <fabric2.runners.Remote object at 0x7f288e314b50>>}

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 834, in handle_stdin
    self.close_proc_stdin()

  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 1067, in close_proc_stdin
    raise NotImplementedError

NotImplementedError

**截图**
![image](https://user-images.githubusercontent.com/67575144/87060964-b98c6180-c23d-11ea-9d9f-7e6d43ba734f.png)
一直卡在这个界面
![image](https://user-images.githubusercontent.com/67575144/87061263-1d168f00-c23e-11ea-9e9c-8ae3f9f4d33f.png)

**运行环境**
![image](https://user-images.githubusercontent.com/67575144/87061047-d5900300-c23d-11ea-82a5-e9fc5fefbd9d.png)

**Comment by BILLFuYiWei** [comment]
补充卡住的界面的图片和运行环境版本图片
![image](https://user-images.githubusercontent.com/67575144/87061537-767ebe00-c23e-11ea-9a36-3bae6b3bf9e4.png)
![image](https://user-images.githubusercontent.com/67575144/87061595-84ccda00-c23e-11ea-9818-3c9b55d8fe7c.png)

**Comment by BILLFuYiWei** [comment]
这个问题已解决  walle2.1版本里fabric2模块版本过低 在宿主机上执行 pip uninstall fabric2; pip install fabric2==2.5.0

**Comment by BILLFuYiWei** [comment]
在记录一个walle2.1 启动时候一个警告    RequestsDependencyWarning: urllib3 (1.24.3) or chardet (2.2.1) doesn't match a supported version!
解决：
requests 版本降到 2.2.0   pip install requests==2.2.0

**Comment by pptfz** [comment]
你们竟然能搭建成功？？？
我这里始终报错后台无法启动，这玩意装了之后也没用，真的是一堆报错
```
ImportError: No module named flask.helpers
Traceback (most recent call last):
  File "waller.py", line 5, in <module>
    from flask.helpers import get_debug_flag
ImportError: No module named flask.helpers
```

**Comment by BILLFuYiWei** [comment]
> 你们竟然能建造成功？？？
> 我这里始终报错后台无法启动，这玩意装了之后也没用，真的是一堆报错
> 
> ```
> ImportError: No module named flask.helpers
> Traceback (most recent call last):
>   File "waller.py", line 5, in <module>
>     from flask.helpers import get_debug_flag
> ImportError: No module named flask.helpers
> ```

walle2.1安装 测试没问题 仔细查看文档 安装步骤 任何一步都不能报错 报错了就要仔细检查  查看walle下error.log日志 常见问题walle文档上就有 没有找到的话就issues里面找找

**Comment by pptfz** [comment]
@BILLFuYiWei  问题已经解决，谢谢回复，使用pip3就能解决依赖关系了，使用pip无法解决，不知道这样是否是正确的方式

**Comment by BILLFuYiWei** [comment]
> @BILLFuYiWei 问题已经解决，谢谢回复，使用pip3就能解决依赖关系了，使用pip无法解决，不知道这样是否是正确的方式

**Comment by BILLFuYiWei** [comment]
> @BILLFuYiWei 问题已经解决，谢谢回复，使用pip3就能解决依赖关系了，使用pip无法解决，不知道这样是否是正确的方式

解决了就好 可以把你碰到的那个依赖有问题贴出来   walle2.1版本过程 或者  启动后遇到的问题都是各种 依赖版本号关系
