### ISSUE TITLE
sh admin.sh migration Migration: [ fail ] BUG

### ISSUE THREAD

**Issue by lingcarzy** [meolu/walle-web#1132]
**问题描述**
sh admin.sh init 执行没问题
walle/config/settings_prod.py已经修改

Migration walle
----------------
Traceback (most recent call last):
  File "/var/www/html/walle-web/venv/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/var/www/html/walle-web/venv/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/var/www/html/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
  File "/var/www/html/walle-web/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 948
    exec(code, globs, locs)
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables
Migration:                 [ fail ]

**运行环境**
 - OS:  Centos 7.1
python 2.7.5
 - 版本 4321cba

**Comment by allenzlr** [comment]
新部署安装walle 2.0 ，遇到了同样的问题。
[root@walle walle-web]# sh admin.sh migration
Migration walle
----------------
Traceback (most recent call last):
  File "/root/walle-web/venv/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/root/walle-web/venv/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/root/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
  File "/root/walle-web/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 948
    exec(code, globs, locs)
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables
Migration:                 [ fail ]

**Comment by allenzlr** [comment]
> **问题描**

是python版本的问题，升级成python3.6再尝试重新安装。我已经部署成功了

**Comment by lsqpy** [comment]
有人解决吗
