### ISSUE TITLE
> **问题描**我升级了Python到3.6了，使用python查看也显示是3.6版本的。也重启过了。但是显示的还是同样的错误，它还是用2.7的Python执行。这种应该怎么解决？

### ISSUE THREAD

**Issue by OneZeroTwoFour** [meolu/walle-web#1135]
> **问题描**

是python版本的问题，升级成python3.6再尝试重新安装。我已经部署成功了

_Originally posted by @allenzlr in https://github.com/meolu/walle-web/issues/1132#issuecomment-680414394_

**Comment by imuxi** [comment]
同样遇到了问题。python版本是3.6.12，
如果/usr/bin/python指向3.6.12，在init就执行不过去
如果/usr/bin/python指向2.7，init可以过去，但是`sh admin.sh migration`就报错误
```
Traceback (most recent call last):
  File "/usr/local/walle-web/venv/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/usr/local/walle-web/venv/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
  File "/usr/local/walle-web/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 948
    exec(code, globs, locs)
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables
Migration:                 [ fail ]
```

@lingcarzy  老兄是怎么解决的

**Comment by OneZeroTwoFour** [comment]
我搞了个walle 1.0  PHP版本的  Python搞不定，第一语言不是Python。

**Comment by lingcarzy** [comment]
init执行有问题 ,可以手动执行下admin.sh里面对应的流程，看看具体是哪一步的问题。然后根据具体的问题来解决。
python最好还是用3.6的版本，2.7在migration那一步是过不去的。

**Comment by lsqpy** [comment]
坑爹

**Comment by OptimisticZombie** [comment]
因为你用2.x版本装过，即便安装好了3.x版本，软连接的还是2.x版本，所以还会包2.x版本，exec的bug。
解决办法：删掉整个文件夹，重新下载。
如果/usr/bin/python已经连到3.x版本，那记得更改yum的python版本，将/usr/bin/yum的python 换成你原来的python版本，例如/usr/bin/python2.7
重新执行init，如果遇到pip问题，先检测是不是pip没有开启，如果还有No module named 'pip._internal' 这种问题，那说明pip组件有问题，重新安装pip就行了。
我是2.75版本，遇到基本上就这些问题，一步步来最后解决了。

**Comment by OptimisticZombie** [comment]
> 因为你用2.x版本装过，即便安装好了3.x版本，软连接的还是2.x版本，所以还会包2.x版本，exec的bug。
> 解决办法：删掉整个文件夹，重新下载。
> 如果/usr/bin/python已经连到3.x版本，那记得更改yum的python版本，将/usr/bin/yum的python 换成你原来的python版本，例如/usr/bin/python2.7
> 重新执行init，如果遇到pip问题，先检测是不是pip没有开启，如果还有No module named 'pip._internal' 这种问题，那说明pip组件有问题，重新安装pip就行了。
> 我是2.75版本，遇到基本上就这些问题，一步步来最后解决了。

对了，安装的python要和pip版本一致，https://bootstrap.pypa.io/  去这里查看和下载你安装的python版本对应的pip
