### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xuanxiaoyu69** [meolu/walle-web#1138]
sh admin.sh migration

Migration walle
----------------
Traceback (most recent call last):
  File "/home/wwwroot/walle-web/venv/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/home/wwwroot/walle-web/venv/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/home/wwwroot/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
  File "/home/wwwroot/walle-web/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 948
    exec(code, globs, locs)
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables
Migration:                 [ fail ]

**没有找到日志**

CentOS Linux release 7.8.2003 (Core)

Linux version 3.10.0-1062.9.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Fri Dec 6 15:49:49 UTC 2019

**Comment by lsqpy** [comment]
有人解决吗？

**Comment by dengjf5603** [comment]
我也是卡在这里，centos 7.6，用的系统自带的python2.7.5
