### ISSUE TITLE
安装错误 错误: cannot import name 'Feature' from 'setuptools'

### ISSUE THREAD

**Issue by wanghaotian0224** [meolu/walle-web#1154]
报错信息
![image](https://user-images.githubusercontent.com/41067842/103398479-dfa11780-4b77-11eb-8fd8-2fb8f3a3ea89.png)

Collecting MarkupSafe==1.0
  Downloading http://pypi.doubanio.com/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/walle/venv/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-izrybqjq/markupsafe_3244a7016a19430a9e2c8479ff7732ea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-izrybqjq/markupsafe_3244a7016a19430a9e2c8479ff7732ea/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rmnk0_7q
         cwd: /tmp/pip-install-izrybqjq/markupsafe_3244a7016a19430a9e2c8479ff7732ea/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-izrybqjq/markupsafe_3244a7016a19430a9e2c8479ff7732ea/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/walle/venv/lib/python3.9/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
************************************************
 init walle success 
 welcome to walle 2.0 

操作系统
centos7 64位

python版本
Python 3.9.1

pip版本
pip 20.3.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

setuptools版本
Name: setuptools
Version: 45.2.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/local/lib/python3.9/site-packages
Requires: 
Required-by:

**Comment by 13233032535** [comment]
哥们，我也遇到了一样的问题，请问您解决了吗?

**Comment by feko2018** [comment]
sed -i '/MarkupSafe==1.0/c MarkupSafe==1.1.0' requirements/prod.txt
