### ISSUE TITLE
docker部署java项目无法上线

### ISSUE THREAD

**Issue by Mrzhuhanxin** [meolu/walle-web#1156]
**问题描述**
在`角色`下，什么页面，什么功能，报错：xx
|在`super超管`角色下，项目管理页面，编辑项目成员，提交失败，报错：用户不存在于空间用户组中

**问题描述**
日志堆栈贴上来。
logs/runtime.log

63b3f6db6e99457f97680f77424ee424: Sending packet MESSAGE data 2/walle,["fail",{"data":{"message":"\u4efb\u52a1\u90e8\u7f72\u5931\u8d25\uff0c\u5df2\u7ec8\u6b62\u3002\u8bf7\u4fee\u590d\u9519\u8bef\u540e\uff0c\u91cd\u65b0\u90e8\u7f72\u3002"},"event":"finish"}]
63b3f6db6e99457f97680f77424ee424: Received packet MESSAGE data 2/walle,["deploy",{"task":"1"}]
received event "deploy" from 63b3f6db6e99457f97680f77424ee424 [/walle]
[2021-01-13 13:50:20,700] ERROR in waller: {'COMMIT_ID': '21aade9', 'BRANCH': '"master"', 'DEPLOY_USER': 'Mrz', 'WALLE_PLUGINS_DIR': '/opt/walle_home/plugins', 'DEPLOY_TIME': '20210113-13:50:19', 'WEBROOT': '/data/script/drink-bluebird-test', 'VERSION': '1_1_20210113_135019', 'PROJECT_ID': '1', 'PROJECT_NAME': '"drink-bluebird"', 'TASK_ID': '1', 'CURRENT_RELEASE': '/data/script/release', 'TAG': '', 'TASK_NAME': '"test"', 'WALLE_HOME': '/opt/walle_home'}
emitting event "console" to 1 [/walle]
63b3f6db6e99457f97680f77424ee424: Sending packet MESSAGE data 2/walle,["console",{"data":{"status":0,"host":"127.0.0.1","error":"","user":"root","success":"","sequence":2,"cmd":"cp -rf /opt/walle_home/codebase/1 1_1_20210113_135019","stage":"deploy"},"event":"task:console"}]
[2021-01-13 13:50:21,829] ERROR in waller: {'COMMIT_ID': '21aade9', 'BRANCH': '"master"', 'DEPLOY_USER': 'Mrz', 'WALLE_PLUGINS_DIR': '/opt/walle_home/plugins', 'DEPLOY_TIME': '20210113-13:50:19', 'WEBROOT': '/data/script/drink-bluebird-test', 'VERSION': '1_1_20210113_135019', 'PROJECT_ID': '1', 'PROJECT_NAME': '"drink-bluebird"', 'TASK_ID': '1', 'CURRENT_RELEASE': '/data/script/release', 'TAG': '', 'TASK_NAME': '"test"', 'WALLE_HOME': '/opt/walle_home'}
Error: JAVA_HOME is not defined correctly.
  We cannot execute 
[2021-01-13 13:50:21,850] ERROR in waller: Error: JAVA_HOME is not defined correctly.
  We cannot execute 
Traceback (most recent call last):
  File "/opt/walle_home/walle/service/waller.py", line 58, in run
    raise Exception(stderr)
Exception: Error: JAVA_HOME is not defined correctly.
  We cannot execute 

[2021-01-13 13:50:21,854] ERROR in waller: task_id=1, user:root host:127.0.0.1 command:sh mvnw clean install -Dmaven.test.skip -Dmaven.source.skip -U, status=1, message:Error: JAVA_HOME is not defined correctly.
  We cannot execute 
Traceback (most recent call last):
  File "/opt/walle_home/walle/service/waller.py", line 58, in run
    raise Exception(stderr)
Exception: Error: JAVA_HOME is not defined correctly.
  We cannot execute 

emitting event "console" to 1 [/walle]
63b3f6db6e99457f97680f77424ee424: Sending packet MESSAGE data 2/walle,["console",{"data":{"status":1,"host":"127.0.0.1","error":"Error: JAVA_HOME is not defined correctly.\r\n  We cannot execute \r\n","user":"root","success":"","sequence":3,"cmd":"sh mvnw clean install -Dmaven.test.skip -Dmaven.source.skip -U","stage":"post_deploy"},"event":"console"}]
[2021-01-13 13:50:21,862] ERROR in waller: {'COMMIT_ID': '21aade9', 'BRANCH': '"master"', 'DEPLOY_USER': 'Mrz', 'WALLE_PLUGINS_DIR': '/opt/walle_home/plugins', 'DEPLOY_TIME': '20210113-13:50:19', 'WEBROOT': '/data/script/drink-bluebird-test', 'VERSION': '1_1_20210113_135019', 'PROJECT_ID': '1', 'PROJECT_NAME': '"drink-bluebird"', 'TASK_ID': '1', 'CURRENT_RELEASE': '/data/script/release', 'TAG': '', 'TASK_NAME': '"test"', 'WALLE_HOME': '/opt/walle_home'}
emitting event "console" to 1 [/walle]
63b3f6db6e99457f97680f77424ee424: Sending packet MESSAGE data 2/walle,["console",{"data":{"status":0,"host":"127.0.0.1","error":"","user":"root","success":"","sequence":3,"cmd":"rm -rf 1_1_*","stage":"post_deploy"},"event":"task:console"}]
emitting event "fail" to 1 [/walle]

```
runtime...
[root@127.0.0.1]$ cp -rf /opt/walle_home/codebase/1 1_1_20210113_135019
[root@127.0.0.1]$ sh mvnw clean install -Dmaven.test.skip -Dmaven.source.skip -U
Error: JAVA_HOME is not defined correctly.
We cannot execute
[root@127.0.0.1]$ rm -rf 1_1_*
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传
![微信图片_20210113135221](https://user-images.githubusercontent.com/43130589/104412112-9eacf800-55a6-11eb-8df7-c3c288b06af9.png)

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. aba77b36] walle首页信息处显示

**Comment by kowinner12** [comment]
JAVA_HOME is not defined correctly 这个提示不是很明显了吗 
全局变量里定义宿主机的JAVA_HOME

**Comment by Mrzhuhanxin** [comment]
### 都配置了，所以就很奇怪

![微信图片_20210118110625](https://user-images.githubusercontent.com/43130589/104868330-08018200-597e-11eb-8378-469000de9ecd.png)
![微信图片_20210118111048](https://user-images.githubusercontent.com/43130589/104868339-0d5ecc80-597e-11eb-818d-b2d5f8ee6c9c.png)
![微信图片_20210118111138](https://user-images.githubusercontent.com/43130589/104868345-1059bd00-597e-11eb-9fe5-2719f0a74a67.png)

**Comment by kowinner12** [comment]
无法打开图片，你可以发下我邮箱里shiyonghui44504@163.com

**Comment by Mrzhuhanxin** [comment]
好的
