### ISSUE TITLE
yum update 后报错

### ISSUE THREAD

**Issue by sn01615** [meolu/walle-web#386]
```
上线出错:（

初始化部署隔离空间出错::'ERROR! Unexpected Exception, this is probably a bug: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=11.3')) the full traceback was: Traceback (most recent call last): File "/usr/bin/ansible", line 85, in mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass) File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 38, in from ansible.inventory.manager import InventoryManager File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 29, in from ansible.inventory.data import InventoryData File "/usr/lib/python2.7/site-packages/ansible/inventory/data.py", line 30, in from ansible.plugins.cache import FactCache File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 30, in from ansible.plugins.loader import cache_loader File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 22, in from ansible.parsing.plugin_docs import read_docstring File "/usr/lib/python2.7/site-packages/ansible/parsing/plugin_docs.py", line 12, in from ansible.parsing.yaml.loader import AnsibleLoader File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/loader.py", line 30, in from ansible.parsing.yaml.constructor import AnsibleConstructor File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/constructor.py", line 29, in from ansible.parsing.vault import VaultLib File "/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 44, in from cryptography.hazmat.backends import default_backend File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in import pkg_resources File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in parse_requirements(__requires__), Environment() File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve raise VersionConflict(dist,req) # XXX put more info here VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=11.3'))'
'ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=false' ansible 'all' -u 'xxxx' -m shell -a 'mkdir -p /mnt/www/releases/xxx/20171106-181440' -i '/mnt/data/wwwroot/walle-web/runtime/ansible_hosts/project_1' -f 10 -T 600' 

请联系SA或者重新部署
```

**Comment by sn01615** [comment]
不知道为啥自己好了
