### ISSUE TITLE
预发布环境，部署接口报错。 PHP Notice 'yii\base\ErrorException' with message 'Undefined index: command' 

### ISSUE THREAD

**Issue by df007df** [meolu/walle-web#392]
预发布环境，点击“部署”，一个接口报错，
在此请求又好了。为什么尼？
地址：/walle/get-process?taskId=24

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: command' 

in /home/deploy/deploy/walle-web/controllers/WalleController.php:379

Stack trace:
#0 /home/deploy/deploy/walle-web/controllers/WalleController.php(379): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/home/deploy/de...', 379, Array)
#1 [internal function]: app\controllers\WalleController->actionGetProcess('24')
#2 /home/deploy/deploy/walle-web/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#3 /home/deploy/deploy/walle-web/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#4 /home/deploy/deploy/walle-web/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('get-process', Array)
#5 /home/deploy/deploy/walle-web/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('walle/get-proce...', Array)
#6 /home/deploy/deploy/walle-web/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 /home/deploy/deploy/walle-web/web/index.php(11): yii\base\Application->run()
#8 {main}

```

**Comment by littlehz** [comment]
可能代码健壮性的问题
