### ISSUE TITLE
get-process  throw index 'command' undefine in WalleController line 379

### ISSUE THREAD

**Issue by xiaofeng890703** [meolu/walle-web#438]
when I am deploying it reports this problem:
[error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: command in /www/sites/server/DeployServer/controllers/WalleController.php:379
Stack trace:
#0 /www/sites/server/DeployServer/controllers/WalleController.php(379): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/www/sites/serv...', 379, Array)
#1 [internal function]: app\controllers\WalleController->actionGetProcess('133')
#2 /www/sites/server/DeployServer/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /www/sites/server/DeployServer/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /www/sites/server/DeployServer/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('get-process', Array)
#5 /www/sites/server/DeployServer/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('walle/get-proce...', Array)
#6 /www/sites/server/DeployServer/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 /www/sites/server/DeployServer/web/index.php(11): yii\base\Application->run()
#8 {main}

**Comment by xiaofeng890703** [comment]
I think it need to write like below

$record['memo'] = isset($record['memo']) ? stripslashes($record['memo']) : '';
 $record['command'] = isset($record['command']) ? stripslashes($record['command']) : '';

**Comment by xiaofeng890703** [comment]
这个bug可以让我来修复吗？

**Comment by sn01615** [comment]
我也遇到这个问题。
解决步骤：
1. 恢复composer.lock 文件
2. 删除vendor目录
3. 执行composer install
