### ISSUE TITLE
Error: While importing "waller", an ImportError was raised:

### ISSUE THREAD

**Issue by chengjun2018** [meolu/walle-web#512]
**问题**：错误信息
样例：执行flask db upgrade 后提示/data/www/walle-web/venv/lib/python2.7/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "waller", an ImportError was raised:

Traceback (most recent call last):
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/data/www/walle-web/waller.py", line 6, in <module>
    from walle.app import create_app
  File "/data/www/walle-web/walle/app.py", line 12, in <module>
    from walle.api import deploy as DeployAPI
  File "/data/www/walle-web/walle/api/deploy.py", line 14, in <module>
    from walle.service.deployer import Deployer
  File "/data/www/walle-web/walle/service/deployer.py", line 15, in <module>
    from walle.service.waller import Waller
ImportError: cannot import name Waller

**解决**：
重新拉取2.0代码，修改数据库连接参数；
怀疑还有其他的问题

**Comment by meolu** [comment]
`sh admin.sh init`没完成，把依赖安装完成
