### ISSUE TITLE
创建上线单页面，提示：网络异常，xxxx

### ISSUE THREAD

**Issue by haozi3156666** [meolu/walle-web#518]
**问题描述**
在 Owner 下，创建上线单页面，进去报错：网络异常，xxxx

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
[2018-12-11 11:19:30,894] ERROR in waller: task_id=0, user:nginx host:127.0.0.1 command:pwd && git clone git@172.12.0.11:blockc/emac.git ., status=1, message:Authentication failed.
[2018-12-11 11:19:30,976] ERROR in waller: Authentication failed.
[2018-12-11 11:19:30,981] ERROR in waller: task_id=0, user:nginx host:127.0.0.1 command:git pull, status=1, message:Authentication failed.
[2018-12-11 11:19:31,062] ERROR in waller: Authentication failed.
[2018-12-11 11:19:31,064] ERROR in waller: task_id=0, user:nginx host:127.0.0.1 command:git branch -r, status=1, message:Authentication failed.
Traceback (most recent call last):
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/geventwebsocket/handler.py", line 87, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/engineio/middleware.py", line 67, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data/www/walle-web2/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data/www/walle-web2/walle/api/repo.py", line 30, in get
    return self_action(project_id=project_id)
  File "/data/www/walle-web2/walle/api/repo.py", line 57, in branches
    branches = wi.list_branch()
  File "/data/www/walle-web2/walle/service/deployer.py", line 341, in list_branch
    branches = color_clean(result.stdout.strip())
AttributeError: 'bool' object has no attribute 'stdout'
2018-12-11T03:19:31Z {'REMOTE_PORT': '54578', 'HTTP_HOST': 'webservers', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 26)} failed with AttributeError
```
logs/error.log
```
2018-12-11 11:19:31,062 ERROR /data/www/walle-web2/walle/service/waller.py 74 waller.run Authentication failed.
2018-12-11 11:19:31,064 ERROR /data/www/walle-web2/walle/service/waller.py 100 waller.run task_id=0, user:nginx host:127.0.0.1 command:git branch -r, status=1, message:Authentication failed.
```

**截图**
手动以 nginx 用户创建目录正常，git clone 也正常
![image](https://user-images.githubusercontent.com/6301977/49776600-9e8efe00-fd37-11e8-828f-6a3a859d1297.png)

**运行环境**
Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018

**Comment by chengjun2018** [comment]
一样的问题，www创建文件目录clone 都没问题
![image](https://user-images.githubusercontent.com/35955748/49844888-238d1c80-fdf7-11e8-9b4d-8ad514764097.png)

宿>>>>>目标主机  免密OK 
![image](https://user-images.githubusercontent.com/35955748/49844629-58e53a80-fdf6-11e8-99bc-aafbd0a54d34.png)
服务启动用户：
![image](https://user-images.githubusercontent.com/35955748/49844973-6bac3f00-fdf7-11e8-91bb-4dcb665983a3.png)

@meolu

**Comment by meolu** [comment]
解决于[523](https://github.com/meolu/walle-web/issues/523#issuecomment-446897813)
