### ISSUE TITLE
上线单刷新 网络连接故障_根据#53的配置并没有解决 +Authentication failed.

### ISSUE THREAD

**Issue by chengjun2018** [meolu/walle-web#521]
Traceback (most recent call last):
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/geventwebsocket/handler.py", line 87, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/engineio/middleware.py", line 67, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data/www/walle-web/walle/api/repo.py", line 30, in get
    return self_action(project_id=project_id)
  File "/data/www/walle-web/walle/api/repo.py", line 44, in tags
    tags = tag_list.stdout.strip().split('\n')
AttributeError: 'bool' object has no attribute 'stdout'
2018-12-12T05:54:54Z {'REMOTE_PORT': '51394', 'HTTP_HOST': 'webservers', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 26)} failed with AttributeError

![image](https://user-images.githubusercontent.com/35955748/49849689-5e01b400-fe0d-11e8-836e-35fed16f4674.png)
#2身份认证失败
![image](https://user-images.githubusercontent.com/35955748/49849906-28a99600-fe0e-11e8-8cd1-7f4f350883d1.png)
https://github.com/meolu/walle-web/issues/518#issuecomment-446447573
https://github.com/meolu/walle-web/issues/518#issuecomment-446448554

**Comment by hyschumi** [comment]
ssh-copy-id user@127.0.0.1?

**Comment by chengjun2018** [comment]
> ssh-copy-id user@127.0.0.1?

是的已经将公钥copy到目标主机，且已经加入gitlab的sshkey中

**Comment by meolu** [comment]
@chengjun2018 麻烦更新下代码，把`logs/error.log`贴下，帮你解决下
