### ISSUE TITLE
centos7 python 3.4使用预览版，直接报错TypeError: dict_values is not JSON serializable

### ISSUE THREAD

**Issue by wu0407** [meolu/walle-web#532]
**问题描述**
在`super超管`角色下，登陆后的界面，/api/general/menu这个接口500

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
[2018-12-14 20:21:27,599] ERROR in api: unkown code 0
nohup: ignoring input
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 304-690-871
[2018-12-14 20:23:18,530] INFO in app: 1
[2018-12-14 20:23:18,872] ERROR in api: unkown code 0
Traceback (most recent call last):
  File "/data/venv/lib/python3.4/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data/venv/lib/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/venv/lib/python3.4/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/venv/lib/python3.4/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/data/venv/lib/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/venv/lib/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/venv/lib/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/venv/lib/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/venv/lib/python3.4/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/data/venv/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/venv/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/venv/lib/python3.4/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/data/venv/lib/python3.4/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data/venv/lib/python3.4/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data/venv/lib/python3.4/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/hgfs/walle-web/walle/service/rbac/role.py", line 57, in decorator
    return func(*args, **kwargs)
  File "/mnt/hgfs/walle-web/walle/api/general.py", line 38, in get
    return self_action()
  File "/mnt/hgfs/walle-web/walle/api/general.py", line 71, in menu
    return self.render_json(data=data)
  File "/mnt/hgfs/walle-web/walle/api/api.py", line 31, in render_json
    return ApiResource.json(code=code, message=message, data=data)
  File "/mnt/hgfs/walle-web/walle/api/api.py", line 44, in json
    'data': data,
  File "/data/venv/lib/python3.4/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/data/venv/lib/python3.4/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib64/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.4/json/encoder.py", line 194, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/venv/lib/python3.4/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib64/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([{'title': '首页', 'icon': 'wl-icon-main', 'sub_menu': [], 'url': '/'}, {'title': '空间管理', 'icon': 'wl-icon-space-set', 'sub_menu': [], 'url': '/admin/space/index'}, {'title': '用户管理', 'icon': 'wl-icon-user-set', 'sub_menu': [], 'url': '/admin/user/index'}, {'title': '项目中心', 'icon': 'wl-icon-project-set', 'sub_menu': [{'title': '环境管理', 'icon': 'leaf', 'url': '/admin/environment/index'}, {'title': '服务器管理', 'icon': 'leaf', 'url': '/admin/server/index'}, {'title': '项目管理', 'icon': 'leaf', 'url': '/admin/project/index'}]}, {'title': '部署管理', 'icon': 'wl-icon-deploy-set', 'sub_menu': [], 'url': '/admin/deploy/index'}]) is not JSON serializable
```
logs/error.log
```
2018-12-14 20:21:27,599 ERROR /mnt/hgfs/walle-web/walle/api/api.py 36 api.json unkown code 0
2018-12-14 20:23:18,872 ERROR /mnt/hgfs/walle-web/walle/api/api.py 36 api.json unkown code 0
2018-12-14 20:24:41,118 ERROR /mnt/hgfs/walle-web/walle/api/api.py 36 api.json unkown code 0
2018-12-14 21:47:44,551 ERROR /mnt/hgfs/walle-web/walle/api/api.py 36 api.json unkown code 0
```

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]预览版
 - mysql community 5.6

顺便提一下，数据库必须是5.6.5版本以上，要不数据库初始化直接报错，自带的marridb5.5直接报错
https://dba.stackexchange.com/questions/152513/error-1067-42000-at-line-7-invalid-default-value-for-last-updated

**Comment by meolu** [comment]
谢谢修复，现在py3还没有做兼容性
