### ISSUE TITLE
更新2.0.0版本后 数据库报故障

### ISSUE THREAD

**Issue by chengjun2018** [meolu/walle-web#569]
File "/data/www/walle-web/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'servers.user' in 'field list'") [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT servers.id AS servers_id, servers.name AS servers_name, servers.host AS servers_host, servers.user AS servers_user, servers.port AS servers_port, servers.status AS servers_status, servers.created_at AS servers_created_at, servers.updated_at AS servers_updated_at \nFROM servers \nWHERE servers.status NOT IN (%s)) AS anon_1'] [parameters: (-1,)] (Background on this error at: http://sqlalche.me/e/e3q8)
Server initialized for gevent.
 * Restarting with stat
Server initialized for gevent.
 * Debugger is active!
 * Debugger PIN: 605-593-558
Traceback (most recent call last):
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/data/www/walle-web/walle/service/rbac/role.py", line 95, in decorator
    return func(*args, **kwargs)
  File "/data/www/walle-web/walle/api/server.py", line 31, in get
    return self.item(id) if id else self.list()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/data/www/walle-web/walle/service/rbac/role.py", line 95, in decorator
    return func(*args, **kwargs)
  File "/data/www/walle-web/walle/api/server.py", line 46, in list
    server_list, count = server_model.list(page=page, size=size, kw=kw)
  File "/data/www/walle-web/walle/model/server.py", line 44, in list
    count = query.count()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3230, in count
    return self.from_self(col).scalar()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2983, in scalar
    ret = self.one()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2954, in one
    ret = self.one_or_none()
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
    ret = list(self)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/data/www/walle-web/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
`

>###  **OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'servers.user' in 'field list'") [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT servers.id AS servers_id, servers.name AS servers_name, servers.host AS servers_host, servers.user AS servers_user, servers.port AS servers_port, servers.status AS servers_status, servers.created_at AS servers_created_at, servers.updated_at AS servers_updated_at \nFROM servers \nWHERE servers.status NOT IN (%s)) AS anon_1'] [parameters: (-1,)] (Background on this error at: http://sqlalche.me/e/e3q8)**

`
![image](https://user-images.githubusercontent.com/35955748/50641045-51e6bd80-0f99-11e9-8d22-a714f9d494e3.png)
![image](https://user-images.githubusercontent.com/35955748/50641098-7c387b00-0f99-11e9-817d-6a6070dbbd69.png)
更新2.0.0后数据库的改变
![image](https://user-images.githubusercontent.com/35955748/50641324-27493480-0f9a-11e9-9b0d-355d78dbc247.png)

排除权限以及互信的操作
![image](https://user-images.githubusercontent.com/35955748/50641428-74c5a180-0f9a-11e9-8f51-3b2353e9eed6.png)

大佬，给看看吧

**Comment by meolu** [comment]
migration没有执行，按文档的升级方式来。
[http://walle-web.io/docs/upgrade.html](http://walle-web.io/docs/upgrade.html)

**Comment by chengjun2018** [comment]
![image](https://user-images.githubusercontent.com/35955748/50670509-ab350800-0ffe-11e9-9d67-1ad2bca7f0ae.png)
请关注一下

**Comment by chengjun2018** [comment]
![image](https://user-images.githubusercontent.com/35955748/50675681-28be3f80-1022-11e9-81e7-a263bc447f73.png)
咨询一下，分发部署到远端机器的文件，不是gitlab上最新的版本。是什么情况
