### ISSUE TITLE
登陆报错

### ISSUE THREAD

**Issue by raofei03** [meolu/walle-web#576]
**问题描述**
在`super超管`角色下，登陆后，报网络异常。

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
#runtime
Traceback (most recent call last):
  File "/srv/walle/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/walle/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/walle/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/walle/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/walle/walle/service/rbac/role.py", line 111, in decorator
    return func(*args, **kwargs)
  File "/srv/walle/walle/api/general.py", line 40, in get
    return self_action()
  File "/srv/walle/walle/api/general.py", line 101, in info
    branch, commit = ''
ValueError: need more than 0 values to unpack
```
![image](https://user-images.githubusercontent.com/8861286/50755045-b607cb00-1292-11e9-8ad3-763db6029806.png)

**运行环境**
 - OS: [e.g. Centos 7.5]
 - 版本 [e.g. 2.0.0]

**Comment by meolu** [comment]
嗯，还真是个问题，少赋值了变量。

已修复，请更新使用
