### ISSUE TITLE
BUG:删除用户在添加出现500错误

### ISSUE THREAD

**Issue by bangbao** [meolu/walle-web#578]
**问题描述**
|在`super超管`角色下，用户管理页面，新建用户后删除在重复新建，提交失败，出现500错误
看了下数据库里users表,  发现 删除用户时只是把 status 标记为-1, 再次添加同样username的用户出现500错误. 

日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
```
Traceback (most recent call last):
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data/work/walle-web/walle/api/user.py", line 88, in post
    return self.create_user()
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/data/work/walle-web/walle/service/rbac/role.py", line 95, in decorator
    return func(*args, **kwargs)
  File "/data/work/walle-web/walle/api/user.py", line 96, in create_user
    user = UserModel().add(user_info)
  File "/data/work/walle-web/walle/model/user.py", line 58, in add
    db.session.commit()
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/data/work/walle-web/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'admin' for key 'idx_username'") [SQL: u'INSERT INTO users (username, is_email_verified, email, password, avatar, `role`, status, last_space, created_at, updated_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: ('admin', 0, '131231@126.com', 'pbkdf2:sha256:50000$wlhc14w1$673fa786758e85eb6314e157c247f041c0112e5bbe41800c0f3680da62115b94', None, '', 1, 0, datetime.datetime(2019, 1, 7, 15, 39, 38, 279880), datetime.datetime(2019, 1, 7, 15, 39, 38, 279880))] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**运行环境**
 - OS: [e.g. Ubuntu18.04]
 - 版本 [e.g. 2.0.0]

**Comment by meolu** [comment]
数据库migration的时候出了问题，最简单粗暴的办法，可以把库drop了，然后重新`sh admin.sh migration`

**Comment by flying1020** [comment]
这个 bug 应该在 https://github.com/meolu/walle-web/commit/57c77057a8a4dbcf09716c17943f158cc0fe19ab 这次提交中已经解决了。

**Comment by ZouHongxue** [comment]
> 这个 bug 应该在 [57c7705](https://github.com/meolu/walle-web/commit/57c77057a8a4dbcf09716c17943f158cc0fe19ab) 这次提交中已经解决了。

我感觉删除操作是不是直接做成数据删除好些, 毕竟也没有提供删除用户恢复的功能。
