### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xliyq** [meolu/walle-web#579]
**问题描述**
启动命令 admin.sh start 出现错误
nohup: ignoring input
Traceback (most recent call last):
  File "waller.py", line 6, in <module>
    from walle.app import create_app
  File "D:\DevSpace\walle-web\walle\app.py", line 10, in <module>
    from walle.api import access as AccessAPI
  File "D:\DevSpace\walle-web\walle\api\access.py", line 13, in <module>
    from walle.api.api import SecurityResource
  File "D:\DevSpace\walle-web\walle\api\api.py", line 12, in <module>
    from walle.service.rbac.access import Access as AccessRbac
  File "D:\DevSpace\walle-web\walle\service\rbac\access.py", line 13, in <module>
    from flask_login import current_user
ModuleNotFoundError: No module named 'flask_login'

**运行环境**
 - OS:  windows 10 
 - 版本 2.0.0

**Comment by meolu** [comment]
首先啊，不要装在win上，光解答问题就耗光我的时间了
