### ISSUE TITLE
项目检测时报错 error: Int or String expected

### ISSUE THREAD

**Issue by xingyueGK** [meolu/walle-web#603]
项目检测时报错
error: Int or String expected
[2019-01-10 10:03:37,426] ERROR in waller: task_id=0, user:user00 host:192.168.107.39 command:[ -L "/data/walle" ] && echo "true" || echo "false", status=1, message:Int or String expected
Traceback (most recent call last):
  File "/data/walle-web/walle/service/waller.py", line 53, in run
    result = super(Waller, self).run(command, pty=pty, warn=True, watchers=[say_yes()], env=self.custom_global_env, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/data/walle-web/venv/lib/python2.7/site-packages/fabric2/connection.py", line 29, in opens
    self.open()
  File "/data/walle-web/venv/lib/python2.7/site-packages/fabric2/connection.py", line 541, in open
    self.client.connect(**kwargs)
  File "/data/walle-web/venv/lib/python2.7/site-packages/paramiko/client.py", line 334, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/data/walle-web/venv/lib/python2.7/site-packages/paramiko/client.py", line 204, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
  File "/data/walle-web/venv/lib/python2.7/site-packages/gevent/_socketcommon.py", line 196, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
  File "/data/walle-web/venv/lib/python2.7/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/data/walle-web/venv/lib/python2.7/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "/data/walle-web/venv/lib/python2.7/site-packages/gevent/threadpool.py", line 281, in _worker

**Comment by wangbeiyong1** [comment]
这个问题解决了吗？公司想用下，看来要失望了
