### ISSUE TITLE
首页报错：网络异常，请刷新重试

### ISSUE THREAD

**Issue by a735465047** [meolu/walle-web#618]
**问题描述**
owner角色下，首页报错：网络异常，请刷新重试

**问题描述**
日志堆栈贴上来。
logs/runtime.log
Traceback (most recent call last):
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data0/www/htdocs/walle-web/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/data0/www/htdocs/walle-web/walle/service/rbac/role.py", line 111, in decorator
    return func(*args, **kwargs)
  File "/data0/www/htdocs/walle-web/walle/api/general.py", line 40, in get
    return self_action()
  File "/data0/www/htdocs/walle-web/walle/api/general.py", line 101, in info
    branch, commit = ''
ValueError: need more than 0 values to unpack
runtime...
```
logs/error.log
```
error...
```

**截图**



**运行环境**
 - OS: centos 7
 - 版本 [e.g. 2.0.0]

**Comment by feihuazaixian** [comment]
出了同样的问题。

**Comment by meolu** [comment]
更新下master，[1d4e9278](https://github.com/meolu/walle-web/commit/1d4e92780b77156fc1fcf6b4ce888f9a4e403ea6) 之前已经修复

**Comment by meolu** [comment]
应该是下载了2.0.0 tag，这个问题没有在tag包里修复

**Comment by hupinxiao** [comment]
我用Dokcer 首次跑起来也会出现这问题，Down掉之后在跑起来就好了。

**Comment by Alenx58** [comment]
你好，无论是标准安装还是docker部署，启动Python后端服务，正常监听5000端口都需要30秒的时间，在这段访问都会出现网络异常的现象。
