### ISSUE TITLE
无法上传更新个人头像

### ISSUE THREAD

**Issue by luckydog85** [meolu/walle-web#629]
**问题描述**
在`super`下，个人中心页面 ，上传头像 https://walle.360che.com/api/user/1/avatar ，报错：TypeError: get() got an unexpected keyword argument 'action'

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
TypeError: get() got an unexpected keyword argument 'action'
Traceback (most recent call last):
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data/web/walle.360che.com/walle-web/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/data/web/walle.360che.com/walle-web/walle/service/rbac/role.py", line 95, in decorator
    return func(*args, **kwargs)
TypeError: get() got an unexpected keyword argument 'action'


```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传
![image](https://user-images.githubusercontent.com/10277372/51176470-ed602280-18f7-11e9-8167-2d6ccddda3b6.png)
![image](https://user-images.githubusercontent.com/10277372/51176503-036de300-18f8-11e9-9515-28add0dada40.png)

**运行环境**
 - OS: [e.g. CentOS Linux release 7.6.1810 (Core)]
 - 版本 [e.g. 2.0.0]

**Comment by chenfengjuan** [comment]
原因：应该是因为头像上传这个接口是http访问的
你可以暂时使用http访问页面，就可以修改了。等我修复下支持https，就好了
