### ISSUE TITLE
socket.io 服务无法连接

### ISSUE THREAD

**Issue by IanGely** [meolu/walle-web#679]
**问题描述**
|在`owner`角色下，进入新建上线单页面，连接 socket.io 服务器报 500 错误

**问题描述**
上线的时候，进入项目新建上线单页面，连接 socket.io 服务器三次 均报 500 Internal Server Error 错误

nginx.conf
```
upstream webservers {
    server 0.0.0.0:8089  weight=1; #域名设置
}

server {
    listen       80;
    server_name  mydomain.com; # 域名设置
    access_log   /var/log/nginx/walle.log main;
    index index.html index.htm; # 日志目录

    location / {
        try_files $uri $uri/ /index.html;
        add_header access-control-allow-origin *;
        root /root/walle-web/fe; # 前端代码已集成到walle-web，即walle-web/fe的绝对路径
    }

    location ^~ /api/ {
        add_header access-control-allow-origin *;
        proxy_pass      http://webservers;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header    Origin        $host:$server_port;
        proxy_set_header    Referer       $host:$server_port;
    }

    location ^~ /socket.io/ {
        add_header access-control-allow-origin *;
        proxy_pass      http://webservers;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header    Origin        $host:$server_port;
        proxy_set_header    Referer       $host:$server_port;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        # WebScoket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

walle/config/settings_prod.py
```
# -*- coding: utf-8 -*-
"""
    walle-web
    Application configuration.
    注意: 带了 @TODO 的地方可能需要你的调整

    :copyright: © 2015-2019 walle-web.io
    :created time: 2018-11-24 07:05:35
    :author: wushuiyong@walle-web.io
"""

import os
from walle.config.settings import Config


class ProdConfig(Config):
    """Production configuration."""
    ENV = 'prod'
    DEBUG = False
    SQLALCHEMY_ECHO = False

    # 服务启动 @TODO
    # HOST 修改为与 nginx server_name 一致.
    # 后续在web hooks与通知中用到此域名.
    HOST = 'mydomain.com'
    PORT = 8089
    # https True, http False
    SSL = False

    # 数据库设置 @TODO
    SQLALCHEMY_DATABASE_URI = 'xxx'

    # 本地代码检出路径（用户查询分支, 编译, 打包） #TODO
    CODE_BASE = '/data/walle/codebase/'

    # 日志存储路径 @TODO
    # 默认为walle-web项目下logs, 可自定义路径, 需以 / 结尾
    # LOG_PATH = '/var/logs/walle/'
    LOG_PATH = os.path.join(Config.PROJECT_ROOT, 'logs')
    LOG_PATH_ERROR = os.path.join(LOG_PATH, 'error.log')
    LOG_PATH_INFO = os.path.join(LOG_PATH, 'info.log')
    LOG_FILE_MAX_BYTES = 100 * 1024 * 1024

    # 邮箱配置 @TODO
    MAIL_SERVER = 'smtp.exmail.qq.com'
    MAIL_PORT = 465
    MAIL_USE_SSL = True
    MAIL_USE_TLS = False
    MAIL_DEFAULT_SENDER = '*'
    MAIL_USERNAME = 'service@walle-web.io'
    MAIL_PASSWORD = 'Ki9y&3U82'
```
logs/runtime.log
```
Traceback (most recent call last):
  File "/root/walle-web/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/root/walle-web/venv/lib/python2.7/site-packages/geventwebsocket/handler.py", line 87, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/root/walle-web/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/root/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/walle-web/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/root/walle-web/venv/lib/python2.7/site-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/root/walle-web/venv/lib/python2.7/site-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/root/walle-web/venv/lib/python2.7/site-packages/engineio/server.py", line 333, in handle_request
    transport, b64)
  File "/root/walle-web/venv/lib/python2.7/site-packages/engineio/server.py", line 454, in _handle_connect
    s = socket.Socket(self, sid)
  File "/root/walle-web/venv/lib/python2.7/site-packages/engineio/socket.py", line 17, in __init__
    self.queue = self.server.create_queue()
  File "/root/walle-web/venv/lib/python2.7/site-packages/engineio/server.py", line 430, in create_queue
    sys.modules[queue.__class__.__module__], 'Empty')
AttributeError: 'gevent._queue.JoinableQueue' object has no attribute 'Empty'
2019-01-25T02:22:08Z {'REMOTE_PORT': '53158', 'HTTP_HOST': mydomain.com', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 30)} failed with AttributeError
```
logs/error.log
```

```

**截图**
<img width="1392" alt="qq20190125-103803 2x" src="https://user-images.githubusercontent.com/3928779/51721570-5df00780-208d-11e9-80ac-0ef72f9c8f05.png">

**运行环境**
 - OS: [Centos 7.6.1810]
 - 版本 [2.0.0]

**Comment by BelieveCode** [comment]
前几天我是从2.0.0版本升级到2.0.1版本也是有这个问题，昨天晚上全部删除掉，然后重新直接安装2.0.1版本就正常了。
