### ISSUE TITLE
BUG - UnboundLocalError: local variable 'members' referenced before assignment // Werkzeug Debugger

### ISSUE THREAD

**Issue by youbuwei** [meolu/walle-web#685]
**问题描述**
在`super超管`角色下，空间管理页面，编辑空间，提示网络异常, 请刷新重试，但数据保存成功

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
Traceback (most recent call last):
  File "/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/walle-web/walle/api/space.py", line 112, in put
    return self.update(space_id)
  File "/walle-web/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/walle-web/walle/service/rbac/role.py", line 79, in decorator
    return func(*args, **kwargs)
  File "/walle-web/walle/api/space.py", line 136, in update
    MemberModel(group_id=space_id).update_group(members=members)
UnboundLocalError: local variable 'members' referenced before assignment
```
logs/error.log
```
error...
```

**截图**
![image](https://user-images.githubusercontent.com/1303345/52029821-ee2bc200-254f-11e9-8097-34fd97a6ec79.png)

**运行环境**
 - OS: CentOS 7.2
 - 版本 2.0.0

**Comment by meolu** [comment]
已修复
