### ISSUE TITLE
空间管理更换空间所属人，提示网络异常，但是空间所属人已更换

### ISSUE THREAD

**Issue by ScorpioJipson** [meolu/walle-web#687]
**问题描述**
在super下，空间管理更换空间所属人，提示网络异常，但是刷新页面后空间所属人已更换

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
UnboundLocalError: local variable 'members' referenced before assignment
Traceback (most recent call last):
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data/web/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data/web/walle-web/walle/api/space.py", line 112, in put
runtime...
```
logs/error.log
```
error...
```

**截图**
![mq y22b6 ytn27 5 rk4v85](https://user-images.githubusercontent.com/24888578/52100059-d0726180-2610-11e9-9405-c510b9cafa8a.png)

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by zhangzl1213** [comment]
未稳定复现，待查

**Comment by meolu** [comment]
已修复
