### ISSUE TITLE
提交上线单已经成功，但是还是提示上线失败，错误信息如下：

### ISSUE THREAD

**Issue by lvxj** [meolu/walle-web#716]
2019-02-25 10:33:16,997 ERROR /opt/walle-web/walle/model/task.py 201 task.enable 1
2019-02-25 10:33:16,997 ERROR /opt/walle-web/walle/model/task.py 202 task.enable 3
2019-02-25 10:33:17,912 ERROR /opt/walle-web/walle/model/task.py 201 task.enable 0
2019-02-25 10:33:17,913 ERROR /opt/walle-web/walle/model/task.py 202 task.enable 3
2019-02-25 10:33:17,968 ERROR /opt/walle-web/walle/model/task.py 201 task.enable 0
2019-02-25 10:33:17,968 ERROR /opt/walle-web/walle/model/task.py 202 task.enable 3
2019-02-25 10:33:19,625 ERROR /opt/walle-web/walle/model/task.py 201 task.enable 0
2019-02-25 10:33:19,625 ERROR /opt/walle-web/walle/model/task.py 202 task.enable 3
2019-02-25 10:33:19,650 ERROR /opt/walle-web/walle/model/task.py 201 task.enable 1
2019-02-25 10:33:19,650 ERROR /opt/walle-web/walle/model/task.py 202 task.enable 3

**Comment by meolu** [comment]
更新版本，重新发布一次帖日志

**Comment by lvxj** [comment]
更新了代码，重新发布 错误日志如下（发送成功消息时候出错了，没通知到）：
c1aa311744674525955f55a5d2b7dadd: Sending packet MESSAGE data 2/walle,["success",{"data":{"host":"192.168.10.252","message":"192.168.10.252 \u90e8\u7f72\u5b8c\u6210\uff01"},"event":"finish"}]
message handler error
Traceback (most recent call last):
  File "/publish/walle-web/venv/lib/python2.7/site-packages/engineio/server.py", line 505, in _trigger_event
    return self.handlers[event](*args)
  File "/publish/walle-web/venv/lib/python2.7/site-packages/socketio/server.py", line 590, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/publish/walle-web/venv/lib/python2.7/site-packages/socketio/server.py", line 526, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/publish/walle-web/venv/lib/python2.7/site-packages/socketio/server.py", line 529, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/publish/walle-web/venv/lib/python2.7/site-packages/socketio/server.py", line 563, in _trigger_event
    event, *args)
  File "/publish/walle-web/venv/lib/python2.7/site-packages/flask_socketio/namespace.py", line 26, in trigger_event
    *args)
  File "/publish/walle-web/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "/publish/walle-web/walle/service/websocket.py", line 55, in on_deploy
    wi.walle_deploy()
  File "/publish/walle-web/walle/service/deployer.py", line 527, in walle_deploy
    self.end(False)
  File "/publish/walle-web/walle/service/deployer.py", line 484, in end
    notice.deploy_task(project_info=self.project_info, notice_info=notice_info)
  File "/publish/walle-web/walle/service/notice/email.py", line 38, in deploy_task
    emails.send_email(project_info['notice_hook'], notice_info['title'], message, '')
  File "/publish/walle-web/walle/service/emails.py", line 47, in send_email
    return mail.send(message)
  File "/publish/walle-web/venv/lib/python2.7/site-packages/flask_mail.py", line 416, in send
    message.send(connection)
  File "/publish/walle-web/venv/lib/python2.7/site-packages/flask_mail.py", line 351, in send
    connection.send(self)
  File "/publish/walle-web/venv/lib/python2.7/site-packages/flask_mail.py", line 168, in send
    message.as_string())
  File "/usr/lib64/python2.7/smtplib.py", line 735, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (501, '\xcf\xb5\xcd\xb3\xd2\xd1\xc7\xbf\xd6\xc6\xbf\xaa\xc6\xf4\xd5\xca\xba\xc5\xc9\xfd\xbc\xb6\xc9\xe8\xd6\xc3\xa3\xac\xc7\xeb\xb5\xc7\xc2\xbcexmail.qq.com\xb0\xf3\xb6\xa8\xce\xa2\xd0\xc5', 'service@walle-web.io')
