### ISSUE TITLE
开发人员查看项目时报错

### ISSUE THREAD

**Issue by changeyourt** [meolu/walle-web#762]
**问题描述**
在开发者角色下，项目管理页面，点击某个项目后的查看按钮，点击会报错：网络错误，请刷新重试。
报错消失后，项目详情可以看到。多次重试，都是如此。

日志无报错。

**截图**
![look](https://user-images.githubusercontent.com/45409457/53930420-2896fa80-40cc-11e9-8444-9b3fdb9e6166.png)

**运行环境**
 - OS:  Centos 7.5
 - 版本 3.1
docker部署方式

**Comment by liuqingliu** [comment]
我这也会报错，但是日志提示如下
Traceback (most recent call last):
  File "/walle-web/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/walle-web/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/walle-web/venv/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/walle-web/venv/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/walle-web/venv/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/walle-web/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/walle-web/walle/service/rbac/role.py", line 97, in decorator
    raise WalleError(Code.not_allow)
WalleError

**Comment by liuqingliu** [comment]
![image](https://user-images.githubusercontent.com/12824514/54117325-717fe380-442b-11e9-8140-58ce64314814.png)
 
将开发者在分配空间权限的时候，填为master权限，项目权限填为developer权限，便一切正常。。。 @changeyourt
