### ISSUE TITLE
已建立SSH互信,但仍然报not a valid RSA private key file

### ISSUE THREAD

**Issue by yhbdyx** [meolu/walle-web#780]
**问题描述**
在`空间所有者`下，部署项目，报错：not a valid RSA private key file

已建立SSH互信

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
ERROR in waller: task_id=0, user:root host:10.0.3.91 command:[ -L "/home/app/sequence-service" ] && echo "true" || echo "false", status=1, message:not a valid RSA private key file
Traceback (most recent call last):
  File "/home/walle/walle/service/waller.py", line 53, in run
    result = super(Waller, self).run(command, pty=pty, warn=True, watchers=[say_yes()], env=self.custom_global_env, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric2/connection.py", line 29, in opens
    self.open()
  File "/usr/lib/python2.7/site-packages/fabric2/connection.py", line 541, in open
    self.client.connect(**kwargs)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. 2.0.0]

**Comment by yhbdyx** [comment]
看附件 , 有个scp语句 , 能正常支持 , SSH互信是没问题的

**Comment by yhbdyx** [comment]
![image](https://user-images.githubusercontent.com/15727811/54276541-91004300-45c8-11e9-8760-2ade3520c5b8.png)

**Comment by yhbdyx** [comment]
重新生成ssh key已解决问题
