### ISSUE TITLE
服务无法启动，端口没有被占用

### ISSUE THREAD

**Issue by wtwei** [meolu/walle-web#838]
**问题描述**
服务无法启动，5000端口没有被占用，这是什么原因导致的呢

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
Server initialized for gevent.
Exception in thread socket_thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/www/walle-web/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 556, in run
    self.wsgi_server.serve_forever()
  File "/mnt/www/walle-web/venv/lib/python2.7/site-packages/gevent/baseserver.py", line 362, in serve_forever
    self.start()
  File "/mnt/www/walle-web/venv/lib/python2.7/site-packages/gevent/baseserver.py", line 306, in start
    self.init_socket()
  File "/mnt/www/walle-web/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 1487, in init_socket
    StreamServer.init_socket(self)
  File "/mnt/www/walle-web/venv/lib/python2.7/site-packages/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/mnt/www/walle-web/venv/lib/python2.7/site-packages/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/mnt/www/walle-web/venv/lib/python2.7/site-packages/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
error: [Errno 99] Cannot assign requested address: ('walle-web.dev.com', 5000)
```

**截图**
![menu saveimg savepath20190408160453](https://user-images.githubusercontent.com/685615/55730857-b0fe1780-5a4b-11e9-9761-27f597cab9e9.jpg)

**运行环境**
 - OS: Centos 7.4
 - 版本:2.0

**Comment by wtwei** [comment]
找到原因了，以为在线上部署就不用修改host了


```
vi /etc/hosts
# 新增一行
127.0.0.1  admin.walle-web.io # 与nginx配置一致
--

```

**Comment by bestlake** [comment]
一样的问题，终于看到希望了！

**Comment by flying1020** [comment]
解决了就好。
有任何问题请随时提交 issue。

**Comment by gipee** [comment]
请问怎么解决

**Comment by Shealtiel-Li** [comment]
该怎么结局呢？

**Comment by Shealtiel-Li** [comment]
解决
