### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by FarmerLi** [meolu/walle-web#875]
**问题描述**
构建时，vue项目不知道是时间过长还是什么原因会抛异常
**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
runtime...
```
logs/error.log
2019-04-23 16:15:29,519 ERROR /home/www/walle-web/walle/service/deployer.py 505 deployer.walle_deploy tar (child): 5_50_20190423_161345.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/home/www/loupan.com-web/walle-web/walle/service/deployer.py", line 496, in walle_deploy
    self.prev_release(self.connections[self.task_id])
  File "/home/www/walle-web/walle/service/deployer.py", line 250, in prev_release
    self.release_untar(waller)
  File "/home/www/walle-web/walle/service/deployer.py", line 333, in release_untar
    result = waller.run(command, wenv=self.config())
  File "/home/www/walle-web/walle/service/waller.py", line 128, in run
    raise e
Exception: tar (child): 5_50_20190423_161345.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
error...
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. aba77b36] walle首页信息处显示

**Comment by tiyilon** [comment]
上面的错误看起来像tar的时候失败. 确定vue的build结果正常么? 然后tar 是否已经打出文件包?  话说 大佬们能否在日志里干脆把运行的命令也打一下吧.有时候看日志都不知道命令行跑了啥导致的错误.

**Comment by FarmerLi** [comment]
build 成功了，并且能够正常发布，但是偶尔会报这个异常，然后中断了，需要重新创建上线单，重新执行

**Comment by FarmerLi** [comment]
![image](https://user-images.githubusercontent.com/2025505/56645451-46d2ad00-66b0-11e9-8061-03fbc5001597.png)

**Comment by FarmerLi** [comment]
![image](https://user-images.githubusercontent.com/2025505/56782694-d005f300-681a-11e9-88cd-580a539bb6a9.png)

**Comment by czy** [comment]
我也经常遇到这个问题。正常流程是：1. 打包.tgz文件，2. scp远程拷贝，3. 删除.tgz文件。出问题时变成了：1. 打包.tgz文件，2. 删除.tgz文件，3. scp远程拷贝。于是就报错了
我怀疑是因为vue build时间过长造成的。

**Comment by deanzhang** [comment]
这个bug我们也不停出现，scp还没拷贝，就已经删除了tgz包

**Comment by boolw** [comment]
这个bug我知道什么问题，是超时问题，你可以发布的时候 sleep 120直接就出现了，但是没有找到怎么解决

**Comment by boolw** [comment]
**解决**
```
walle/service/deployer.py
第428行-关键字`cleanup_local`
command = 'rm -rf {project_id}_{task_id}_*'.format(project_id=self.project_info['id'], task_id=self.task_id)

修改为：

command = 'ls -t ./ | grep "^{project_id}_" | tail -n +{keep_version_num} | xargs rm -rf'.format(project_id=self.project_info['id'], keep_version_num=int(self.project_info['keep_version_num']) + 1)
```

**Comment by opszone** [comment]
我想请教下怎么部署vue项目，该在哪个位置设置npm install。

**Comment by AviorAlong** [comment]
> 我想请教下怎么部署vue项目，该在哪个位置设置npm install。

你哪里需要npm 包就在哪安装，如果在Deploy阶段编译，编译的机器上肯定需要npm install，业务机肯定需要npm install 除非你把编译下载的node_modules copy过去

**Comment by opszone** [comment]
是不是每次发布的时候都得npm install 一遍呢？我命令行能执行，为什么walle就报错
![image](https://user-images.githubusercontent.com/31090716/76499848-73371980-647a-11ea-8f33-6a80a1e659ac.png)

**Comment by opszone** [comment]
[root@127.0.0.1]$ /usr/bin/npm install
internal/modules/cjs/loader.js:985
throw err;
^
Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /usr/bin/npm
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
at Function.Module._load (internal/modules/cjs/loader.js:864:27)
at Module.require (internal/modules/cjs/loader.js:1044:19)
at require (internal/modules/cjs/helpers.js:77:18)
at /usr/bin/npm:19:21
at Object.<anonymous> (/usr/bin/npm:153:3)
at Module._compile (internal/modules/cjs/loader.js:1158:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
at Module.load (internal/modules/cjs/loader.js:1002:32)
at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/usr/bin/npm' ]
}

**Comment by AviorAlong** [comment]
> [root@127.0.0.1]$ /usr/bin/npm install
> internal/modules/cjs/loader.js:985
> throw err;
> ^
> Error: Cannot find module '../lib/utils/unsupported.js'
> Require stack:
> 
> * /usr/bin/npm
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:864:27)
>   at Module.require (internal/modules/cjs/loader.js:1044:19)
>   at require (internal/modules/cjs/helpers.js:77:18)
>   at /usr/bin/npm:19:21
>   at Object. (/usr/bin/npm:153:3)
>   at Module._compile (internal/modules/cjs/loader.js:1158:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>   at Module.load (internal/modules/cjs/loader.js:1002:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/usr/bin/npm' ]
>   }

 /usr/bin/npm 和你自己执行npm 是同一个npm吗？

**Comment by opszone** [comment]
发布VUE项目的时候，是不是每次都得npm install 一遍呢？

**Comment by AviorAlong** [comment]
> 发布VUE项目的时候，是不是每次都得npm install 一遍呢？

自己控制，理论上有引入新包才需要npm install，关键是你怎么控制这个，如果npm版本大于5，lock文件会控制版本，即使你每次npm install，也无所谓，如果小于5，为了避免装包耗时，自己diff package.json吧，没变化就不装了

**Comment by boolw** [comment]
我一般只第一次npm install，后面把node_modules拷贝到其它目录，打包的时候 创建一个软连接到打包目录就可以了，编译失败最好是自己手动编译一次看能编译成功不

**Comment by opszone** [comment]
好的 谢谢您的解惑

**Comment by anota** [comment]
> > 发布VUE项目的时候，是不是每次都得npm install 一遍呢？
> 
> 自己控制，理论上有引入新包才需要npm install，关键是你怎么控制这个，如果npm版本大于5，lock文件会控制版本，即使你每次npm install，也无所谓，如果小于5，为了避免装包耗时，自己diff package.json吧，没变化就不装了

diff 貌似有坑 因为在部署阶段git上的代码已经合并了 没办法diff了
