### ISSUE TITLE
开发者权限，访问项目配置时报错

### ISSUE THREAD

**Issue by FarmerLi** [meolu/walle-web#881]
**问题描述**
在开发者下，查看项目配置页面，报错：
后台服务未启动
请检查日志或者点官网链接查看帮助

**问题描述**
logs/runtime.log
```
[2019-04-24 16:39:00,651] ERROR in app: Exception on /api/server/ [GET]
Traceback (most recent call last):
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/www/walle-web/walle/service/rbac/role.py", line 97, in decorator
    raise WalleError(Code.not_allow)
WalleError
```
logs/error.log
```
2019-04-24 16:33:27,148 ERROR /home/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py 1761 app.log_exception Exception on /api/server/ [GET]
Traceback (most recent call last):
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/www/walle-web/venv/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/www/walle-web/walle/service/rbac/role.py", line 97, in decorator
    raise WalleError(Code.not_allow)
WalleError
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.5]
 - 版本 [e.g. 2.0.1] walle首页信息处显示

**Comment by boxsky** [comment]
同样的问题

**Comment by zcoson** [comment]
应该是开发者没有获取服务器列表的权限，bug
