### ISSUE TITLE
BUG git ssh地址端口非22 上线单显示不了分支

### ISSUE THREAD

**Issue by kayw-geek** [meolu/walle-web#884]
**问题描述**
在`全部角色`下，部署管理页面，获取分支功能 一直获取不到分支

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
emitting event "branches" to 1 [/walle]
02a621dd30a7496c80f0ff5a958699d9: Sending packet MESSAGE data 2/walle,["branches",{"data":{"message":""},"event":"error"}]
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
emitting event "commits" to 1 [/walle]
02a621dd30a7496c80f0ff5a958699d9: Sending packet MESSAGE data 2/walle,["commits",{"data":{"message":""},"event":"error"}]
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
02a621dd30a7496c80f0ff5a958699d9: Received packet PING data None
02a621dd30a7496c80f0ff5a958699d9: Sending packet PONG data None
runtime...
```
logs/error.log
```
2019-04-25 14:13:18,250 ERROR /usr/lib64/python2.7/site-packages/flask/app.py 1761 app.log_exception Exception on /api/server/ [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/html/walle-web/walle/service/rbac/role.py", line 97, in decorator
    raise WalleError(Code.not_allow)
WalleError

error...
```

**截图**
拖拽到此处即可上传
![image](https://user-images.githubusercontent.com/29700073/56719172-ccb72c80-6772-11e9-8e74-5b068aa2eede.png)

**运行环境**
 - OS: [e.g. Centos 7.2]
 - 版本 [e.g. aba77b36] 2.0.1

**Comment by rxqn2008** [comment]
可以进入容器内，git clone 一次试试，能clone下来，并且公钥已经加入到github上了，再退出容器，应该就可以加载出来分支了。可能是首次clone，需要确认下信息造成的
