### ISSUE TITLE
我用docker-compose 安装后，在登录页面不能登录，

### ISSUE THREAD

**Issue by xingyu-Lu** [meolu/walle-web#906]
**问题描述**
在`超管`下 登录页面，登录功能，报错：后台服务未启动

**问题描述**
日志堆栈贴上来。
logs/runtime.log
`walle-python | [2019-05-10 17:08:06,143] ERROR in app: Exception on /api/passport/login [POST]
walle-python | Traceback (most recent call last):
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
walle-python |     rv = self.dispatch_request()
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
walle-python |     return self.view_functions[rule.endpoint](**req.view_args)
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
walle-python |     resp = resource(*args, **kwargs)
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
walle-python |     return self.dispatch_request(*args, **kwargs)
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
walle-python |     resp = meth(*args, **kwargs)
walle-python |   File "/opt/walle_home/walle/api/passport.py", line 34, in post
walle-python |     return self_action()
walle-python |   File "/opt/walle_home/walle/api/passport.py", line 47, in login
walle-python |     user = UserModel.query.filter_by(email=form.email.data).first()
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2895, in first
walle-python |     ret = list(self[0:1])
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
walle-python |     return list(res)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
walle-python |     return self._execute_and_instances(context)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
walle-python |     result = conn.execute(querycontext.statement, self._params)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
walle-python |     return meth(self, multiparams, params)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
walle-python |     return connection._execute_clauseelement(self, multiparams, params)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
walle-python |     compiled_sql, distilled_params
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
walle-python |     context)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
walle-python |     exc_info
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
walle-python |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
walle-python |     context)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
walle-python |     cursor.execute(statement, parameters)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
walle-python |     result = self._query(query)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
walle-python |     conn.query(q)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
walle-python |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
walle-python |     result.read()
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
walle-python |     first_packet = self.connection._read_packet()
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
walle-python |     packet.check_error()
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
walle-python |     err.raise_mysql_exception(self._data)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
walle-python |     raise errorclass(errno, errval)
walle-python | ProgrammingError: (pymysql.err.ProgrammingError) (1146, u"Table 'walle.users' doesn't exist") [SQL: u'SELECT users.id AS users_id, users.username AS users_username, users.is_email_verified AS users_is_email_verified, users.email AS users_email, users.password AS users_password, users.avatar AS users_avatar, users.`role` AS users_role, users.status AS users_status, users.last_space AS users_last_space, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.email = %(email_1)s \n LIMIT %(param_1)s'] [parameters: {u'email_1': u'super@walle-web.io', u'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)
walle-nginx | 192.168.198.1 - - [10/May/2019:17:08:06 +0800] "POST /api/passport/login HTTP/1.1" 500 37 "http://192.168.198.101/login" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" "-"
![1557479063(1)](https://user-images.githubusercontent.com/24647719/57515957-5c99d080-7346-11e9-80fc-7828b86456f8.jpg)
``
runtime...
```
logs/error.log
```
error...
```

**截图**
拖拽到此处即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. aba77b36] walle首页信息处显示

**Comment by Alenx58** [comment]
@xingyu-Lu Hi，你的数据库初始化没有成功，请删除MySQL映射的宿主机目录下的文件，重新数据初始化

**Comment by xingyu-Lu** [comment]
> @xingyu-Lu Hi，你的数据库初始化没有成功，请删除MySQL映射的宿主机目录下的文件，重新数据初始化

解决啦，谢谢
