### ISSUE TITLE
owner空间下添加用户失败

### ISSUE THREAD

**Issue by xingyu-Lu** [meolu/walle-web#909]
**问题描述**
使用docker-compose安装的
在`owner`下，用户管理页面，添加用户功能，报错：后台服务未启动

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
![1557741249(1)](https://user-images.githubusercontent.com/24647719/57612911-4a1ed180-75a8-11e9-8e41-eb68051ade30.jpg)

runtime...
```
logs/error.log
```
walle-python | [2019-05-13 17:49:03,683] ERROR in app: Exception on /api/user/ [POST]
walle-python | Traceback (most recent call last):
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
walle-python |     rv = self.dispatch_request()
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
walle-python |     return self.view_functions[rule.endpoint](**req.view_args)
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
walle-python |     resp = resource(*args, **kwargs)
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
walle-python |     return self.dispatch_request(*args, **kwargs)
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
walle-python |     resp = meth(*args, **kwargs)
walle-python |   File "/opt/walle_home/walle/api/user.py", line 88, in post
walle-python |     return self.create_user()
walle-python |   File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
walle-python |     return func(*args, **kwargs)
walle-python |   File "/opt/walle_home/walle/service/rbac/role.py", line 95, in decorator
walle-python |     return func(*args, **kwargs)
walle-python |   File "/opt/walle_home/walle/api/user.py", line 96, in create_user
walle-python |     user = UserModel().add(user_info)
walle-python |   File "/opt/walle_home/walle/model/user.py", line 58, in add
walle-python |     db.session.commit()
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
walle-python |     return getattr(self.registry(), name)(*args, **kwargs)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
walle-python |     self.transaction.commit()
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
walle-python |     self._prepare_impl()
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
walle-python |     self.session.flush()
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
walle-python |     self._flush(objects)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
walle-python |     transaction.rollback(_capture_exception=True)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
walle-python |     compat.reraise(exc_type, exc_value, exc_tb)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
walle-python |     flush_context.execute()
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
walle-python |     rec.execute(self)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
walle-python |     uow
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
walle-python |     mapper, table, insert)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
walle-python |     execute(statement, params)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
walle-python |     return meth(self, multiparams, params)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
walle-python |     return connection._execute_clauseelement(self, multiparams, params)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
walle-python |     compiled_sql, distilled_params
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
walle-python |     context)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
walle-python |     exc_info
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
walle-python |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
walle-python |     context)
walle-python |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
walle-python |     cursor.execute(statement, parameters)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
walle-python |     result = self._query(query)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
walle-python |     conn.query(q)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
walle-python |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
walle-python |     result.read()
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
walle-python |     first_packet = self.connection._read_packet()
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
walle-python |     packet.check_error()
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
walle-python |     err.raise_mysql_exception(self._data)
walle-python |   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
walle-python |     raise errorclass(errno, errval)
walle-python | IntegrityError: (pymysql.err.IntegrityError) (1062, u"Duplicate entry 'test' for key 'idx_username'") [SQL: u'INSERT INTO users (username, is_email_verified, email, password, avatar, `role`, status, last_space, created_at, updated_at) VALUES (%(username)s, %(is_email_verified)s, %(email)s, %(password)s, %(avatar)s, %(role)s, %(status)s, %(last_space)s, %(created_at)s, %(updated_at)s)'] [parameters: {'username': u'test', 'status': 1, 'last_space': 0, 'created_at': datetime.datetime(2019, 5, 13, 17, 49, 3, 674217), 'updated_at': datetime.datetime(2019, 5, 13, 17, 49, 3, 674255), 'role': '', 'is_email_verified': 0, 'password': 'pbkdf2:sha256:50000$TeKUaYDR$a12d2f08301e9c96fc4c4a1d94203374499d52a428484a38fafe67da6bf3f2f9', 'email': u'testt@163.com', 'avatar': None}] (Background on this error at: http://sqlalche.me/e/gkpj)
walle-nginx | 192.168.198.1 - - [13/May/2019:17:49:03 +0800] "POST /api/user/ HTTP/1.1" 500 37 "http://192.168.198.101/Demo%E7%A9%BA%E9%97%B4/user/index" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" "-"
![1557741249(1)](https://user-images.githubusercontent.com/24647719/57612861-31aeb700-75a8-11e9-9ae2-815e9c14a321.jpg)

```

**截图**
拖拽到此处
![1557741249(1)](https://user-images.githubusercontent.com/24647719/57613007-78041600-75a8-11e9-9411-13654771c2a4.jpg)
即可上传

**运行环境**
 - OS: [e.g. Centos 7.x]
 - 版本 [e.g. aba77b36] walle首页信息处显示

**Comment by xingyu-Lu** [comment]
版本：docker-compose里写的是2.1

**Comment by ZouHongxue** [comment]
![image](https://user-images.githubusercontent.com/20573881/57614915-02e70f80-75ad-11e9-8f0b-fc09210ab360.png)


test这个名字已经存在了！数据库有 unique key

**Comment by xingyu-Lu** [comment]
> ![image](https://user-images.githubusercontent.com/20573881/57614915-02e70f80-75ad-11e9-8f0b-fc09210ab360.png)
> 
> test这个名字已经存在了！数据库有 unique key

我用的testt不是test

**Comment by xingyu-Lu** [comment]
> > ![image](https://user-images.githubusercontent.com/20573881/57614915-02e70f80-75ad-11e9-8f0b-fc09210ab360.png)
> > test这个名字已经存在了！数据库有 unique key
> 
> 我用的testt不是test

![image](https://user-images.githubusercontent.com/24647719/57615133-8f91cd80-75ad-11e9-93f4-e93f560ca866.png)

**Comment by ZouHongxue** [comment]
> > 我用的testt不是test
> 
> ![image](https://user-images.githubusercontent.com/24647719/57615133-8f91cd80-75ad-11e9-93f4-e93f560ca866.png)

麻烦仔细看下日志错误

**Comment by xingyu-Lu** [comment]
> ![image](https://user-images.githubusercontent.com/20573881/57614915-02e70f80-75ad-11e9-8f0b-fc09210ab360.png)
> 
> test这个名字已经存在了！数据库有 unique key

失误，用户名不能用test
