### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by bing086** [meolu/walle-web#931]
**问题描述**
安装完成，启动报错如下。python版本 2.7.16

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
Server initialized for gevent.
Exception in thread socket_thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/www/wwwroot/walle-web/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 556, in run
    self.wsgi_server.serve_forever()
  File "/www/wwwroot/walle-web/venv/lib/python2.7/site-packages/gevent/baseserver.py", line 362, in serve_forever
    self.start()
  File "/www/wwwroot/walle-web/venv/lib/python2.7/site-packages/gevent/baseserver.py", line 306, in start
    self.init_socket()
  File "/www/wwwroot/walle-web/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 1487, in init_socket
    StreamServer.init_socket(self)
  File "/www/wwwroot/walle-web/venv/lib/python2.7/site-packages/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/www/wwwroot/walle-web/venv/lib/python2.7/site-packages/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/www/wwwroot/walle-web/venv/lib/python2.7/site-packages/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
error: [Errno 99] Cannot assign requested address: ('walle.vcoder.club', 5000)

**Comment by niugh** [comment]
是不是端口被占用了
