### ISSUE TITLE
选版本的时候失败了

### ISSUE THREAD

**Issue by jackywdx** [meolu/walle-web#965]
**问题描述**
在`master`角色下，创建上线单页面，点击刷新版本的按钮，报错了，也看不到错误信息

**问题描述**
日志堆栈贴上来。
logs/runtime.log
```
b911058caabc42d3b48c8d4c388b70d7: Received packet MESSAGE data 2/walle,["commits",{"branch":"hotfix/v1903_open_account_white_list"}]
received event "commits" from b911058caabc42d3b48c8d4c388b70d7 [/walle]
emitting event "commits" to 1 [/walle]
b911058caabc42d3b48c8d4c388b70d7: Sending packet MESSAGE data 2/walle,["commits",{"data":{"message":""},"event":"error"}]
b911058caabc42d3b48c8d4c388b70d7: Received packet PING data None
```
logs/error.log
```
2019-07-02 15:28:36,047 ERROR /data/web_publish/walle-web-master/walle/service/waller.py 111 waller.run task_id=0, user:ops host:172.28.249.17 command:[ -L "/data/web_publish/setup_service" ] && echo "true" || echo "false", status=1, message:Authentication failed.
Traceback (most recent call last):
  File "/data/web_publish/walle-web-master/walle/service/waller.py", line 53, in run
    result = super(Waller, self).run(command, pty=pty, warn=True, watchers=[say_yes()], env=self.custom_global_env, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/data/web_publish/walle-web-master/venv/lib/python2.7/site-packages/fabric2/connection.py", line 29, in opens
    self.open()
  File "/data/web_publish/walle-web-master/venv/lib/python2.7/site-packages/fabric2/connection.py", line 541, in open
    self.client.connect(**kwargs)
  File "/data/web_publish/walle-web-master/venv/lib/python2.7/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/data/web_publish/walle-web-master/venv/lib/python2.7/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.
```

**截图**
![1](https://user-images.githubusercontent.com/15396952/60634549-de3b4580-9e41-11e9-8b9b-49e882bd171e.png)

**运行环境**
 - OS: [ Centos 6.8]
 - 版本 [a2959199e013dc42fc4e1dc94eb9c23264857a3f] 

看到另一个BUG也提到这个问题，评论中貌似说了不再需要处理这个宿主机的信任关系了，不确定这里的报错是否有关联

**Comment by damaainan** [comment]
我也遇到了这个问题，更新了几次版本，都不起作用。只能复制一次项目，使用新的项目，但是一段时间后还是会出现这个问题

**Comment by shaukei** [comment]
这个问题很坑，你手动去把/tmp/walle/code???目录删了，就可以选了

**Comment by 376453716** [comment]
一样，复制一个新项目，或者手动删除/tmp/walle/codebase/{projectId}就可以了。
错误提示：
Cmd('git') failed due to: exit code(128) cmdline: git clone -v git@gitlab.beisencorp.com:pps/BeisenWelfare.git /tmp/walle/codebase/24 stderr: 'fatal: destination path '/tmp/walle/codebase/24' already exists and is not an empty directory. '

**Comment by Purelightme** [comment]
遇到同样的问题，请问docker部署的怎么解决？centos7.2

**Comment by Jerrywgl** [comment]
通过重启可以临时解决这个问题，但是一会儿还会出现这个问题

**Comment by Yiipanny** [comment]
vim +428 walle/service/deployer.py

- command = 'rm -rf {project_id}_{task_id}_*'.format(project_id=self.project_info['id'], task_id=self.task_id)
+ command = 'rm -rf {project_id} {project_id}_{task_id}_*'.format(project_id=self.project_info['id'], task_id=self.task_id)

简单粗暴
