### ISSUE TITLE
执行sh admin.sh migration报错

### ISSUE THREAD

**Issue by itzhangqi** [meolu/walle-web#995]
**问题描述**
第一步： sh admin.sh init没有问题;
第二步:  修改walle/config/settings_prod.py 也改了
第三步：执行 sh admin.sh migration时报错：

--
(venv) root@43187ec82c34:/data/wwwroot/walle-web# sh admin.sh migration
                                                                                            
                                                          llllllllllllll                     
                                                           l::::l l::::l                     
wwwwwww           wwwww           wwwwww aaaaaaaaaaaaa     l::::l l::::l     eeeeeeeeeeee    
 w:::::w         w:::::w         w:::::w a::::::::::::a    l::::l l::::l   ee::::::::::::ee  
  w:::::w       w:::::::w       w:::::w  aaaaaaaaa:::::a   l::::l l::::l  e::::::eeeee:::::ee
   w:::::w     w:::::::::w     w:::::w            a::::a   l::::l l::::l e::::::e     e:::::e
    w:::::w   w:::::w:::::w   w:::::w      aaaaaaa:::::a   l::::l l::::l e:::::::eeeee::::::e
     w:::::w w:::::w w:::::w w:::::w     aa::::::::::::a   l::::l l::::l e:::::::::::::::::e 
      w:::::w:::::w   w:::::w:::::w     a::::aaaa::::::a   l::::l l::::l e::::::eeeeeeeeeee  
       w:::::::::w     w:::::::::w     a::::a    a:::::a   l::::l l::::l e:::::::e           
        w:::::::w       w:::::::w      a::::a    a:::::a   l::::l l::::l e::::::::e          
         w:::::w         w:::::w       a:::::aaaa::::::a   l::::l l::::l  e::::::::eeeeeeee  
          w:::w           w:::w         a::::::::::aa::a   l::::: l:::::l  ee:::::::::::::e  
           www             www           aaaaaaaaaa  aaaa llllllllllllllll    eeeeeeeeeeeeee  
                                                                                            
Migration walle
----------------
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "waller", an ImportError was raised:

Traceback (most recent call last):
  File "/data/wwwroot/walle-web/venv/local/lib/python2.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/data/wwwroot/walle-web/waller.py", line 6, in <module>
    from walle.app import create_app
  File "/data/wwwroot/walle-web/walle/app.py", line 16, in <module>
    from walle.api import deploy as DeployAPI
  File "/data/wwwroot/walle-web/venv/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/data/wwwroot/walle-web/walle/api/deploy.py", line 14, in <module>
    from walle.service.deployer import Deployer
  File "/data/wwwroot/walle-web/venv/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/data/wwwroot/walle-web/walle/service/deployer.py", line 25, in <module>
    from walle.service.git.repo import Repo
  File "/data/wwwroot/walle-web/venv/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/data/wwwroot/walle-web/walle/service/git/repo.py", line 14, in <module>
    import git as PyGit
  File "/data/wwwroot/walle-web/venv/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/data/wwwroot/walle-web/venv/local/lib/python2.7/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

Migration:                 [ fail ]

**运行环境**
 - ubuntu: docker创建的ubuntu容器中
 - 版本 [2.0]

**Comment by chenqiuqiang** [comment]
我也有这个问题，到现在都不知道怎么解决。

**Comment by ZouHongxue** [comment]
提示信息里的执行试下
export GIT_PYTHON_REFRESH=quiet
